// ---- GENERATED BY QEDGEN ---- spec-hash:e6bb073cf883379a
//
// Self-contained Kani proof harnesses for the spec.
//
// These proofs verify the spec's transition design using Kani bounded model
// checking. They operate on a pure model of the state machine (derived from
// the qedspec), independent of framework (Quasar/Anchor) types.
//
//   Lean proves:  transition functions preserve invariants (∀ states)
//   Kani checks:  same properties via bounded model checking + overflow detection
//   Together:     high assurance that the spec design is correct
//
// To run:  cargo kani --harness <name>   (requires cargo-kani)
// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
#![cfg(kani)]

// ============================================================================
// State model (derived from qedspec — no framework dependencies)
// ============================================================================

#[derive(Clone, Copy, kani::Arbitrary)]
struct State {
    initialized: u8,
    deadline_slot: u64,
    created_at_slot: u64,
}

#[derive(Clone, Copy)]
struct State {
}

// ============================================================================
// Property predicates (from qedspec `property` declarations)
// ============================================================================

/// registration_terminal: s.initialized = 0 ∨ s.initialized = 1
fn registration_terminal(s: &State) -> bool {
    (s.initialized == 0) || (s.initialized == 1)
}

// ============================================================================
// Transition functions (from qedspec operations — effects + guards)
//
// Each returns true if the guard passes and the transition fires,
// false if the guard rejects the operation.
// ============================================================================

fn register(s: &mut State, deadline_slot: u64, current_slot: u64) -> bool {
    if !(s.initialized == 0) {
        return false;
    }
    s.initialized = 1;
    s.deadline_slot = deadline_slot;
    s.created_at_slot = current_slot;
    true
}

// ============================================================================
// Guard enforcement — transitions reject invalid inputs
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_register_rejects_invalid() {
    let mut s = State {
    };
    let deadline_slot: u64 = kani::any();
    let current_slot: u64 = kani::any();
    kani::assume(!(s.initialized == 0));
    assert!(!register(&mut s, deadline_slot, current_slot),
        "register must reject when guard is violated");
}

// ============================================================================
// Property preservation — invariants hold through all transitions
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_register_preserves_registration_terminal() {
    let mut s = State {
    };
    kani::assume(registration_terminal(&s));
    let deadline_slot: u64 = kani::any();
    let current_slot: u64 = kani::any();
    if register(&mut s, deadline_slot, current_slot) {
        assert!(registration_terminal(&s),
            "registration_terminal must hold after register");
    }
}

// ============================================================================
// Effect conformance — verify transition effects match spec
//
// Each proof applies a transition to symbolic state and checks that every
// field changed/unchanged matches the spec's effect: declarations.
// ============================================================================

// ============================================================================
// Cover properties — reachability via kani::cover!
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn cover_happy_path() {
    let mut s = State {
    };
    let deadline_slot_0: u64 = kani::any();
    let current_slot_0: u64 = kani::any();
    kani::cover!(register(&mut s, deadline_slot_0, current_slot_0), "happy_path trace is reachable");
}

// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
