// ---- GENERATED BY QEDGEN ----
//
// Proptest harnesses — property-based testing for the spec's state machine.
// Tier 1 of the verification waterfall: finds counterexamples in milliseconds.
//
//   Proptest: random testing, fast counterexamples (~100ms)
//   Kani:     bounded model checking, exhaustive within bounds (~5-30s)
//   Lean:     mathematical proof, universal guarantees (minutes-hours)
//
// To run:  cargo test --test proptest
// Deep:    PROPTEST_CASES=10000 cargo test --test proptest
// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----

use proptest::prelude::*;

#[derive(Debug, Clone, Copy)]
struct State {
    initialized: u8,
    deadline_slot: u64,
    created_at_slot: u64,
}

prop_compose! {
    fn arb_State()(initialized in 0u8..=255u8, deadline_slot in 0u64..=u64::MAX, created_at_slot in 0u64..=u64::MAX) -> State {
        State {
            initialized,
            deadline_slot,
            created_at_slot,
        }
    }
}

#[derive(Debug, Clone, Copy)]
struct State {
}

/// Proptest strategy for generating arbitrary State values.
fn arb_state() -> impl Strategy<Value = State> {
    (
,
    ).prop_map(|()| State {
    })
}

/// Boundary-biased strategy for guard rejection tests.
fn arb_boundary_state() -> impl Strategy<Value = State> {
    (
,
    ).prop_map(|()| State {
    })
}

/// registration_terminal: s.initialized = 0 ∨ s.initialized = 1
fn registration_terminal(s: &State) -> bool {
    (s.initialized == 0) || (s.initialized == 1)
}

fn register(s: &mut State, deadline_slot: u64, current_slot: u64) -> bool {
    if !(s.initialized == 0) {
        return false;
    }
    s.initialized = 1;
    s.deadline_slot = deadline_slot;
    s.created_at_slot = current_slot;
    true
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn register_preserves_registration_terminal(s in arb_state(), deadline_slot in 0u64..=u64::MAX, current_slot in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(registration_terminal(&s));
        if register(&mut s, deadline_slot, current_slot) {
            prop_assert!(registration_terminal(&s),
                "registration_terminal must hold after register");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn register_rejects_invalid(s in arb_boundary_state(), deadline_slot in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], current_slot in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX]) {
        let mut s = s;
        prop_assume!(!(s.initialized == 0));
        prop_assert!(!register(&mut s, deadline_slot, current_slot),
            "register must reject when guard is violated");
    }
}

