// ---- GENERATED BY QEDGEN ---- spec-hash:d4bad525e97fc377
//
// Self-contained Kani proof harnesses for the spec.
//
// These proofs verify the spec's transition design using Kani bounded model
// checking. They operate on a pure model of the state machine (derived from
// the qedspec), independent of framework (Quasar/Anchor) types.
//
//   Lean proves:  transition functions preserve invariants (∀ states)
//   Kani checks:  same properties via bounded model checking + overflow detection
//   Together:     high assurance that the spec design is correct
//
// To run:  cargo kani --harness <name>   (requires cargo-kani)
// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
#![cfg(kani)]

// ============================================================================
// State model (derived from qedspec — no framework dependencies)
// ============================================================================

const MAX_FEE_BPS: u16 = 1000;

#[derive(Clone, Copy, kani::Arbitrary)]
struct State {
    initialized: u8,
    status: u8,
    yes_reserves: u64,
    no_reserves: u64,
    fee_bps: u64,
}

#[derive(Clone, Copy)]
struct State {
}

// ============================================================================
// Property predicates (from qedspec `property` declarations)
// ============================================================================

/// swap_no_drain: s.status ≠ 0 ∨ s.yes_reserves > 0 ∨ s.no_reserves > 0
fn swap_no_drain(s: &State) -> bool {
    ((s.status != 0) || (s.yes_reserves > 0)) || (s.no_reserves > 0)
}

/// fee_bps_bounded: s.fee_bps ≤ 1000
fn fee_bps_bounded(s: &State) -> bool {
    s.fee_bps <= 1000
}

/// status_monotone: s.status ≤ 2
fn status_monotone(s: &State) -> bool {
    s.status <= 2
}

// ============================================================================
// Transition functions (from qedspec operations — effects + guards)
//
// Each returns true if the guard passes and the transition fires,
// false if the guard rejects the operation.
// ============================================================================

fn initialize_pool(s: &mut State, subsidy_yes: u64, subsidy_no: u64, fee_bps: u64) -> bool {
    if !(s.initialized == 0 && subsidy_yes > 0 && subsidy_no > 0 && fee_bps <= 1000) {
        return false;
    }
    s.initialized = 1;
    s.status = 0;
    s.yes_reserves = subsidy_yes;
    s.no_reserves = subsidy_no;
    s.fee_bps = fee_bps;
    true
}

fn swap_yes_for_no(s: &mut State, amount_in: u64, amount_out: u64, min_amount_out: u64) -> bool {
    if !(s.status == 0 && amount_in > 0 && amount_out >= min_amount_out && amount_out < s.no_reserves) {
        return false;
    }
    match s.yes_reserves.checked_add(amount_in) {
        Some(__v) => s.yes_reserves = __v,
        None => return false,
    }
    match s.no_reserves.checked_sub(amount_out) {
        Some(__v) => s.no_reserves = __v,
        None => return false,
    }
    true
}

fn swap_no_for_yes(s: &mut State, amount_in: u64, amount_out: u64, min_amount_out: u64) -> bool {
    if !(s.status == 0 && amount_in > 0 && amount_out >= min_amount_out && amount_out < s.yes_reserves) {
        return false;
    }
    match s.no_reserves.checked_add(amount_in) {
        Some(__v) => s.no_reserves = __v,
        None => return false,
    }
    match s.yes_reserves.checked_sub(amount_out) {
        Some(__v) => s.yes_reserves = __v,
        None => return false,
    }
    true
}

fn mark_resolved_yes(s: &mut State) -> bool {
    if !(s.status == 0) {
        return false;
    }
    s.status = 1;
    true
}

fn mark_resolved_no(s: &mut State) -> bool {
    if !(s.status == 0) {
        return false;
    }
    s.status = 2;
    true
}

fn withdraw_yes_after_resolution(s: &mut State, amount: u64) -> bool {
    if !(s.status == 1 && amount > 0 && amount <= s.yes_reserves) {
        return false;
    }
    match s.yes_reserves.checked_sub(amount) {
        Some(__v) => s.yes_reserves = __v,
        None => return false,
    }
    true
}

fn withdraw_no_after_resolution(s: &mut State, amount: u64) -> bool {
    if !(s.status == 2 && amount > 0 && amount <= s.no_reserves) {
        return false;
    }
    match s.no_reserves.checked_sub(amount) {
        Some(__v) => s.no_reserves = __v,
        None => return false,
    }
    true
}

// ============================================================================
// Guard enforcement — transitions reject invalid inputs
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_pool_rejects_invalid() {
    let mut s = State {
    };
    let subsidy_yes: u64 = kani::any();
    let subsidy_no: u64 = kani::any();
    let fee_bps: u64 = kani::any();
    kani::assume(!(s.initialized == 0 && subsidy_yes > 0 && subsidy_no > 0 && fee_bps <= 1000));
    assert!(!initialize_pool(&mut s, subsidy_yes, subsidy_no, fee_bps),
        "initialize_pool must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_swap_yes_for_no_rejects_invalid() {
    let mut s = State {
    };
    let amount_in: u64 = kani::any();
    let amount_out: u64 = kani::any();
    let min_amount_out: u64 = kani::any();
    kani::assume(!(s.status == 0 && amount_in > 0 && amount_out >= min_amount_out && amount_out < s.no_reserves));
    assert!(!swap_yes_for_no(&mut s, amount_in, amount_out, min_amount_out),
        "swap_yes_for_no must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_swap_no_for_yes_rejects_invalid() {
    let mut s = State {
    };
    let amount_in: u64 = kani::any();
    let amount_out: u64 = kani::any();
    let min_amount_out: u64 = kani::any();
    kani::assume(!(s.status == 0 && amount_in > 0 && amount_out >= min_amount_out && amount_out < s.yes_reserves));
    assert!(!swap_no_for_yes(&mut s, amount_in, amount_out, min_amount_out),
        "swap_no_for_yes must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_mark_resolved_yes_rejects_invalid() {
    let mut s = State {
    };
    kani::assume(!(s.status == 0));
    assert!(!mark_resolved_yes(&mut s),
        "mark_resolved_yes must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_mark_resolved_no_rejects_invalid() {
    let mut s = State {
    };
    kani::assume(!(s.status == 0));
    assert!(!mark_resolved_no(&mut s),
        "mark_resolved_no must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_withdraw_yes_after_resolution_rejects_invalid() {
    let mut s = State {
    };
    let amount: u64 = kani::any();
    kani::assume(!(s.status == 1 && amount > 0 && amount <= s.yes_reserves));
    assert!(!withdraw_yes_after_resolution(&mut s, amount),
        "withdraw_yes_after_resolution must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_withdraw_no_after_resolution_rejects_invalid() {
    let mut s = State {
    };
    let amount: u64 = kani::any();
    kani::assume(!(s.status == 2 && amount > 0 && amount <= s.no_reserves));
    assert!(!withdraw_no_after_resolution(&mut s, amount),
        "withdraw_no_after_resolution must reject when guard is violated");
}

// ============================================================================
// Property preservation — invariants hold through all transitions
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_pool_preserves_swap_no_drain() {
    let mut s = State {
    };
    kani::assume(swap_no_drain(&s));
    kani::assume(fee_bps_bounded(&s));
    kani::assume(status_monotone(&s));
    let subsidy_yes: u64 = kani::any();
    let subsidy_no: u64 = kani::any();
    let fee_bps: u64 = kani::any();
    if initialize_pool(&mut s, subsidy_yes, subsidy_no, fee_bps) {
        assert!(swap_no_drain(&s),
            "swap_no_drain must hold after initialize_pool");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_swap_yes_for_no_preserves_swap_no_drain() {
    let mut s = State {
    };
    kani::assume(swap_no_drain(&s));
    kani::assume(fee_bps_bounded(&s));
    kani::assume(status_monotone(&s));
    let amount_in: u64 = kani::any();
    let amount_out: u64 = kani::any();
    let min_amount_out: u64 = kani::any();
    if swap_yes_for_no(&mut s, amount_in, amount_out, min_amount_out) {
        assert!(swap_no_drain(&s),
            "swap_no_drain must hold after swap_yes_for_no");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_swap_no_for_yes_preserves_swap_no_drain() {
    let mut s = State {
    };
    kani::assume(swap_no_drain(&s));
    kani::assume(fee_bps_bounded(&s));
    kani::assume(status_monotone(&s));
    let amount_in: u64 = kani::any();
    let amount_out: u64 = kani::any();
    let min_amount_out: u64 = kani::any();
    if swap_no_for_yes(&mut s, amount_in, amount_out, min_amount_out) {
        assert!(swap_no_drain(&s),
            "swap_no_drain must hold after swap_no_for_yes");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_mark_resolved_yes_preserves_swap_no_drain() {
    let mut s = State {
    };
    kani::assume(swap_no_drain(&s));
    kani::assume(fee_bps_bounded(&s));
    kani::assume(status_monotone(&s));
    if mark_resolved_yes(&mut s) {
        assert!(swap_no_drain(&s),
            "swap_no_drain must hold after mark_resolved_yes");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_mark_resolved_no_preserves_swap_no_drain() {
    let mut s = State {
    };
    kani::assume(swap_no_drain(&s));
    kani::assume(fee_bps_bounded(&s));
    kani::assume(status_monotone(&s));
    if mark_resolved_no(&mut s) {
        assert!(swap_no_drain(&s),
            "swap_no_drain must hold after mark_resolved_no");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_withdraw_yes_after_resolution_preserves_swap_no_drain() {
    let mut s = State {
    };
    kani::assume(swap_no_drain(&s));
    kani::assume(fee_bps_bounded(&s));
    kani::assume(status_monotone(&s));
    let amount: u64 = kani::any();
    if withdraw_yes_after_resolution(&mut s, amount) {
        assert!(swap_no_drain(&s),
            "swap_no_drain must hold after withdraw_yes_after_resolution");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_withdraw_no_after_resolution_preserves_swap_no_drain() {
    let mut s = State {
    };
    kani::assume(swap_no_drain(&s));
    kani::assume(fee_bps_bounded(&s));
    kani::assume(status_monotone(&s));
    let amount: u64 = kani::any();
    if withdraw_no_after_resolution(&mut s, amount) {
        assert!(swap_no_drain(&s),
            "swap_no_drain must hold after withdraw_no_after_resolution");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_pool_preserves_fee_bps_bounded() {
    let mut s = State {
    };
    kani::assume(swap_no_drain(&s));
    kani::assume(fee_bps_bounded(&s));
    kani::assume(status_monotone(&s));
    let subsidy_yes: u64 = kani::any();
    let subsidy_no: u64 = kani::any();
    let fee_bps: u64 = kani::any();
    if initialize_pool(&mut s, subsidy_yes, subsidy_no, fee_bps) {
        assert!(fee_bps_bounded(&s),
            "fee_bps_bounded must hold after initialize_pool");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_swap_yes_for_no_preserves_fee_bps_bounded() {
    let mut s = State {
    };
    kani::assume(swap_no_drain(&s));
    kani::assume(fee_bps_bounded(&s));
    kani::assume(status_monotone(&s));
    let amount_in: u64 = kani::any();
    let amount_out: u64 = kani::any();
    let min_amount_out: u64 = kani::any();
    if swap_yes_for_no(&mut s, amount_in, amount_out, min_amount_out) {
        assert!(fee_bps_bounded(&s),
            "fee_bps_bounded must hold after swap_yes_for_no");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_swap_no_for_yes_preserves_fee_bps_bounded() {
    let mut s = State {
    };
    kani::assume(swap_no_drain(&s));
    kani::assume(fee_bps_bounded(&s));
    kani::assume(status_monotone(&s));
    let amount_in: u64 = kani::any();
    let amount_out: u64 = kani::any();
    let min_amount_out: u64 = kani::any();
    if swap_no_for_yes(&mut s, amount_in, amount_out, min_amount_out) {
        assert!(fee_bps_bounded(&s),
            "fee_bps_bounded must hold after swap_no_for_yes");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_mark_resolved_yes_preserves_fee_bps_bounded() {
    let mut s = State {
    };
    kani::assume(swap_no_drain(&s));
    kani::assume(fee_bps_bounded(&s));
    kani::assume(status_monotone(&s));
    if mark_resolved_yes(&mut s) {
        assert!(fee_bps_bounded(&s),
            "fee_bps_bounded must hold after mark_resolved_yes");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_mark_resolved_no_preserves_fee_bps_bounded() {
    let mut s = State {
    };
    kani::assume(swap_no_drain(&s));
    kani::assume(fee_bps_bounded(&s));
    kani::assume(status_monotone(&s));
    if mark_resolved_no(&mut s) {
        assert!(fee_bps_bounded(&s),
            "fee_bps_bounded must hold after mark_resolved_no");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_withdraw_yes_after_resolution_preserves_fee_bps_bounded() {
    let mut s = State {
    };
    kani::assume(swap_no_drain(&s));
    kani::assume(fee_bps_bounded(&s));
    kani::assume(status_monotone(&s));
    let amount: u64 = kani::any();
    if withdraw_yes_after_resolution(&mut s, amount) {
        assert!(fee_bps_bounded(&s),
            "fee_bps_bounded must hold after withdraw_yes_after_resolution");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_withdraw_no_after_resolution_preserves_fee_bps_bounded() {
    let mut s = State {
    };
    kani::assume(swap_no_drain(&s));
    kani::assume(fee_bps_bounded(&s));
    kani::assume(status_monotone(&s));
    let amount: u64 = kani::any();
    if withdraw_no_after_resolution(&mut s, amount) {
        assert!(fee_bps_bounded(&s),
            "fee_bps_bounded must hold after withdraw_no_after_resolution");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_pool_preserves_status_monotone() {
    let mut s = State {
    };
    kani::assume(swap_no_drain(&s));
    kani::assume(fee_bps_bounded(&s));
    kani::assume(status_monotone(&s));
    let subsidy_yes: u64 = kani::any();
    let subsidy_no: u64 = kani::any();
    let fee_bps: u64 = kani::any();
    if initialize_pool(&mut s, subsidy_yes, subsidy_no, fee_bps) {
        assert!(status_monotone(&s),
            "status_monotone must hold after initialize_pool");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_swap_yes_for_no_preserves_status_monotone() {
    let mut s = State {
    };
    kani::assume(swap_no_drain(&s));
    kani::assume(fee_bps_bounded(&s));
    kani::assume(status_monotone(&s));
    let amount_in: u64 = kani::any();
    let amount_out: u64 = kani::any();
    let min_amount_out: u64 = kani::any();
    if swap_yes_for_no(&mut s, amount_in, amount_out, min_amount_out) {
        assert!(status_monotone(&s),
            "status_monotone must hold after swap_yes_for_no");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_swap_no_for_yes_preserves_status_monotone() {
    let mut s = State {
    };
    kani::assume(swap_no_drain(&s));
    kani::assume(fee_bps_bounded(&s));
    kani::assume(status_monotone(&s));
    let amount_in: u64 = kani::any();
    let amount_out: u64 = kani::any();
    let min_amount_out: u64 = kani::any();
    if swap_no_for_yes(&mut s, amount_in, amount_out, min_amount_out) {
        assert!(status_monotone(&s),
            "status_monotone must hold after swap_no_for_yes");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_mark_resolved_yes_preserves_status_monotone() {
    let mut s = State {
    };
    kani::assume(swap_no_drain(&s));
    kani::assume(fee_bps_bounded(&s));
    kani::assume(status_monotone(&s));
    if mark_resolved_yes(&mut s) {
        assert!(status_monotone(&s),
            "status_monotone must hold after mark_resolved_yes");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_mark_resolved_no_preserves_status_monotone() {
    let mut s = State {
    };
    kani::assume(swap_no_drain(&s));
    kani::assume(fee_bps_bounded(&s));
    kani::assume(status_monotone(&s));
    if mark_resolved_no(&mut s) {
        assert!(status_monotone(&s),
            "status_monotone must hold after mark_resolved_no");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_withdraw_yes_after_resolution_preserves_status_monotone() {
    let mut s = State {
    };
    kani::assume(swap_no_drain(&s));
    kani::assume(fee_bps_bounded(&s));
    kani::assume(status_monotone(&s));
    let amount: u64 = kani::any();
    if withdraw_yes_after_resolution(&mut s, amount) {
        assert!(status_monotone(&s),
            "status_monotone must hold after withdraw_yes_after_resolution");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_withdraw_no_after_resolution_preserves_status_monotone() {
    let mut s = State {
    };
    kani::assume(swap_no_drain(&s));
    kani::assume(fee_bps_bounded(&s));
    kani::assume(status_monotone(&s));
    let amount: u64 = kani::any();
    if withdraw_no_after_resolution(&mut s, amount) {
        assert!(status_monotone(&s),
            "status_monotone must hold after withdraw_no_after_resolution");
    }
}

// ============================================================================
// Effect conformance — verify transition effects match spec
//
// Each proof applies a transition to symbolic state and checks that every
// field changed/unchanged matches the spec's effect: declarations.
// ============================================================================

// ============================================================================
// Cover properties — reachability via kani::cover!
// ============================================================================

#[kani::proof]
#[kani::unwind(4)]
#[kani::solver(cadical)]
fn cover_swap_path() {
    let mut s = State {
    };
    let subsidy_yes_0: u64 = kani::any();
    let subsidy_no_0: u64 = kani::any();
    let fee_bps_0: u64 = kani::any();
    if initialize_pool(&mut s, subsidy_yes_0, subsidy_no_0, fee_bps_0) {
        let amount_in_1: u64 = kani::any();
        let amount_out_1: u64 = kani::any();
        let min_amount_out_1: u64 = kani::any();
        if swap_yes_for_no(&mut s, amount_in_1, amount_out_1, min_amount_out_1) {
            let amount_in_2: u64 = kani::any();
            let amount_out_2: u64 = kani::any();
            let min_amount_out_2: u64 = kani::any();
            kani::cover!(swap_no_for_yes(&mut s, amount_in_2, amount_out_2, min_amount_out_2), "swap_path trace is reachable");
        }
    }
}

#[kani::proof]
#[kani::unwind(4)]
#[kani::solver(cadical)]
fn cover_yes_resolution_withdraw() {
    let mut s = State {
    };
    let subsidy_yes_0: u64 = kani::any();
    let subsidy_no_0: u64 = kani::any();
    let fee_bps_0: u64 = kani::any();
    if initialize_pool(&mut s, subsidy_yes_0, subsidy_no_0, fee_bps_0) {
        if mark_resolved_yes(&mut s) {
            let amount_2: u64 = kani::any();
            kani::cover!(withdraw_yes_after_resolution(&mut s, amount_2), "yes_resolution_withdraw trace is reachable");
        }
    }
}

#[kani::proof]
#[kani::unwind(4)]
#[kani::solver(cadical)]
fn cover_no_resolution_withdraw() {
    let mut s = State {
    };
    let subsidy_yes_0: u64 = kani::any();
    let subsidy_no_0: u64 = kani::any();
    let fee_bps_0: u64 = kani::any();
    if initialize_pool(&mut s, subsidy_yes_0, subsidy_no_0, fee_bps_0) {
        if mark_resolved_no(&mut s) {
            let amount_2: u64 = kani::any();
            kani::cover!(withdraw_no_after_resolution(&mut s, amount_2), "no_resolution_withdraw trace is reachable");
        }
    }
}

// ============================================================================
// Overflow detection — Kani catches arithmetic overflow on add effects
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_swap_yes_for_no_no_overflow() {
    let mut s = State {
    };
    let amount_in: u64 = kani::any();
    let amount_out: u64 = kani::any();
    let min_amount_out: u64 = kani::any();
    swap_yes_for_no(&mut s, amount_in, amount_out, min_amount_out);  // Kani detects overflow on += internally
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_swap_no_for_yes_no_overflow() {
    let mut s = State {
    };
    let amount_in: u64 = kani::any();
    let amount_out: u64 = kani::any();
    let min_amount_out: u64 = kani::any();
    swap_no_for_yes(&mut s, amount_in, amount_out, min_amount_out);  // Kani detects overflow on += internally
}

// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
