// ---- GENERATED BY QEDGEN ----
//
// Proptest harnesses — property-based testing for the spec's state machine.
// Tier 1 of the verification waterfall: finds counterexamples in milliseconds.
//
//   Proptest: random testing, fast counterexamples (~100ms)
//   Kani:     bounded model checking, exhaustive within bounds (~5-30s)
//   Lean:     mathematical proof, universal guarantees (minutes-hours)
//
// To run:  cargo test --test proptest
// Deep:    PROPTEST_CASES=10000 cargo test --test proptest
// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----

use proptest::prelude::*;

const MAX_FEE_BPS: u16 = 1000;

#[derive(Debug, Clone, Copy)]
struct State {
    initialized: u8,
    status: u8,
    yes_reserves: u64,
    no_reserves: u64,
    fee_bps: u64,
}

prop_compose! {
    fn arb_State()(initialized in 0u8..=255u8, status in 0u8..=255u8, yes_reserves in 0u64..=u64::MAX, no_reserves in 0u64..=u64::MAX, fee_bps in 0u64..=u64::MAX) -> State {
        State {
            initialized,
            status,
            yes_reserves,
            no_reserves,
            fee_bps,
        }
    }
}

#[derive(Debug, Clone, Copy)]
struct State {
}

/// Proptest strategy for generating arbitrary State values.
fn arb_state() -> impl Strategy<Value = State> {
    (
,
    ).prop_map(|()| State {
    })
}

/// Boundary-biased strategy for guard rejection tests.
fn arb_boundary_state() -> impl Strategy<Value = State> {
    (
,
    ).prop_map(|()| State {
    })
}

/// swap_no_drain: s.status ≠ 0 ∨ s.yes_reserves > 0 ∨ s.no_reserves > 0
fn swap_no_drain(s: &State) -> bool {
    ((s.status != 0) || (s.yes_reserves > 0)) || (s.no_reserves > 0)
}

/// fee_bps_bounded: s.fee_bps ≤ 1000
fn fee_bps_bounded(s: &State) -> bool {
    s.fee_bps <= 1000
}

/// status_monotone: s.status ≤ 2
fn status_monotone(s: &State) -> bool {
    s.status <= 2
}

fn initialize_pool(s: &mut State, subsidy_yes: u64, subsidy_no: u64, fee_bps: u64) -> bool {
    if !(s.initialized == 0 && subsidy_yes > 0 && subsidy_no > 0 && fee_bps <= 1000) {
        return false;
    }
    s.initialized = 1;
    s.status = 0;
    s.yes_reserves = subsidy_yes;
    s.no_reserves = subsidy_no;
    s.fee_bps = fee_bps;
    true
}

fn swap_yes_for_no(s: &mut State, amount_in: u64, amount_out: u64, min_amount_out: u64) -> bool {
    if !(s.status == 0 && amount_in > 0 && amount_out >= min_amount_out && amount_out < s.no_reserves) {
        return false;
    }
    s.yes_reserves = s.yes_reserves.wrapping_add(amount_in);
    s.no_reserves = s.no_reserves.wrapping_sub(amount_out);
    true
}

fn swap_no_for_yes(s: &mut State, amount_in: u64, amount_out: u64, min_amount_out: u64) -> bool {
    if !(s.status == 0 && amount_in > 0 && amount_out >= min_amount_out && amount_out < s.yes_reserves) {
        return false;
    }
    s.no_reserves = s.no_reserves.wrapping_add(amount_in);
    s.yes_reserves = s.yes_reserves.wrapping_sub(amount_out);
    true
}

fn mark_resolved_yes(s: &mut State) -> bool {
    if !(s.status == 0) {
        return false;
    }
    s.status = 1;
    true
}

fn mark_resolved_no(s: &mut State) -> bool {
    if !(s.status == 0) {
        return false;
    }
    s.status = 2;
    true
}

fn withdraw_yes_after_resolution(s: &mut State, amount: u64) -> bool {
    if !(s.status == 1 && amount > 0 && amount <= s.yes_reserves) {
        return false;
    }
    s.yes_reserves = s.yes_reserves.wrapping_sub(amount);
    true
}

fn withdraw_no_after_resolution(s: &mut State, amount: u64) -> bool {
    if !(s.status == 2 && amount > 0 && amount <= s.no_reserves) {
        return false;
    }
    s.no_reserves = s.no_reserves.wrapping_sub(amount);
    true
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn initialize_pool_preserves_swap_no_drain(s in arb_state(), subsidy_yes in 0u64..=u64::MAX, subsidy_no in 0u64..=u64::MAX, fee_bps in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(swap_no_drain(&s));
        prop_assume!(fee_bps_bounded(&s));
        prop_assume!(status_monotone(&s));
        if initialize_pool(&mut s, subsidy_yes, subsidy_no, fee_bps) {
            prop_assert!(swap_no_drain(&s),
                "swap_no_drain must hold after initialize_pool");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn swap_yes_for_no_preserves_swap_no_drain(s in arb_state(), amount_in in 0u64..=u64::MAX, amount_out in 0u64..=u64::MAX, min_amount_out in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(swap_no_drain(&s));
        prop_assume!(fee_bps_bounded(&s));
        prop_assume!(status_monotone(&s));
        if swap_yes_for_no(&mut s, amount_in, amount_out, min_amount_out) {
            prop_assert!(swap_no_drain(&s),
                "swap_no_drain must hold after swap_yes_for_no");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn swap_no_for_yes_preserves_swap_no_drain(s in arb_state(), amount_in in 0u64..=u64::MAX, amount_out in 0u64..=u64::MAX, min_amount_out in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(swap_no_drain(&s));
        prop_assume!(fee_bps_bounded(&s));
        prop_assume!(status_monotone(&s));
        if swap_no_for_yes(&mut s, amount_in, amount_out, min_amount_out) {
            prop_assert!(swap_no_drain(&s),
                "swap_no_drain must hold after swap_no_for_yes");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn mark_resolved_yes_preserves_swap_no_drain(s in arb_state()) {
        let mut s = s;
        prop_assume!(swap_no_drain(&s));
        prop_assume!(fee_bps_bounded(&s));
        prop_assume!(status_monotone(&s));
        if mark_resolved_yes(&mut s) {
            prop_assert!(swap_no_drain(&s),
                "swap_no_drain must hold after mark_resolved_yes");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn mark_resolved_no_preserves_swap_no_drain(s in arb_state()) {
        let mut s = s;
        prop_assume!(swap_no_drain(&s));
        prop_assume!(fee_bps_bounded(&s));
        prop_assume!(status_monotone(&s));
        if mark_resolved_no(&mut s) {
            prop_assert!(swap_no_drain(&s),
                "swap_no_drain must hold after mark_resolved_no");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn withdraw_yes_after_resolution_preserves_swap_no_drain(s in arb_state(), amount in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(swap_no_drain(&s));
        prop_assume!(fee_bps_bounded(&s));
        prop_assume!(status_monotone(&s));
        if withdraw_yes_after_resolution(&mut s, amount) {
            prop_assert!(swap_no_drain(&s),
                "swap_no_drain must hold after withdraw_yes_after_resolution");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn withdraw_no_after_resolution_preserves_swap_no_drain(s in arb_state(), amount in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(swap_no_drain(&s));
        prop_assume!(fee_bps_bounded(&s));
        prop_assume!(status_monotone(&s));
        if withdraw_no_after_resolution(&mut s, amount) {
            prop_assert!(swap_no_drain(&s),
                "swap_no_drain must hold after withdraw_no_after_resolution");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn initialize_pool_preserves_fee_bps_bounded(s in arb_state(), subsidy_yes in 0u64..=u64::MAX, subsidy_no in 0u64..=u64::MAX, fee_bps in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(swap_no_drain(&s));
        prop_assume!(fee_bps_bounded(&s));
        prop_assume!(status_monotone(&s));
        if initialize_pool(&mut s, subsidy_yes, subsidy_no, fee_bps) {
            prop_assert!(fee_bps_bounded(&s),
                "fee_bps_bounded must hold after initialize_pool");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn swap_yes_for_no_preserves_fee_bps_bounded(s in arb_state(), amount_in in 0u64..=u64::MAX, amount_out in 0u64..=u64::MAX, min_amount_out in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(swap_no_drain(&s));
        prop_assume!(fee_bps_bounded(&s));
        prop_assume!(status_monotone(&s));
        if swap_yes_for_no(&mut s, amount_in, amount_out, min_amount_out) {
            prop_assert!(fee_bps_bounded(&s),
                "fee_bps_bounded must hold after swap_yes_for_no");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn swap_no_for_yes_preserves_fee_bps_bounded(s in arb_state(), amount_in in 0u64..=u64::MAX, amount_out in 0u64..=u64::MAX, min_amount_out in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(swap_no_drain(&s));
        prop_assume!(fee_bps_bounded(&s));
        prop_assume!(status_monotone(&s));
        if swap_no_for_yes(&mut s, amount_in, amount_out, min_amount_out) {
            prop_assert!(fee_bps_bounded(&s),
                "fee_bps_bounded must hold after swap_no_for_yes");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn mark_resolved_yes_preserves_fee_bps_bounded(s in arb_state()) {
        let mut s = s;
        prop_assume!(swap_no_drain(&s));
        prop_assume!(fee_bps_bounded(&s));
        prop_assume!(status_monotone(&s));
        if mark_resolved_yes(&mut s) {
            prop_assert!(fee_bps_bounded(&s),
                "fee_bps_bounded must hold after mark_resolved_yes");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn mark_resolved_no_preserves_fee_bps_bounded(s in arb_state()) {
        let mut s = s;
        prop_assume!(swap_no_drain(&s));
        prop_assume!(fee_bps_bounded(&s));
        prop_assume!(status_monotone(&s));
        if mark_resolved_no(&mut s) {
            prop_assert!(fee_bps_bounded(&s),
                "fee_bps_bounded must hold after mark_resolved_no");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn withdraw_yes_after_resolution_preserves_fee_bps_bounded(s in arb_state(), amount in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(swap_no_drain(&s));
        prop_assume!(fee_bps_bounded(&s));
        prop_assume!(status_monotone(&s));
        if withdraw_yes_after_resolution(&mut s, amount) {
            prop_assert!(fee_bps_bounded(&s),
                "fee_bps_bounded must hold after withdraw_yes_after_resolution");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn withdraw_no_after_resolution_preserves_fee_bps_bounded(s in arb_state(), amount in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(swap_no_drain(&s));
        prop_assume!(fee_bps_bounded(&s));
        prop_assume!(status_monotone(&s));
        if withdraw_no_after_resolution(&mut s, amount) {
            prop_assert!(fee_bps_bounded(&s),
                "fee_bps_bounded must hold after withdraw_no_after_resolution");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn initialize_pool_preserves_status_monotone(s in arb_state(), subsidy_yes in 0u64..=u64::MAX, subsidy_no in 0u64..=u64::MAX, fee_bps in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(swap_no_drain(&s));
        prop_assume!(fee_bps_bounded(&s));
        prop_assume!(status_monotone(&s));
        if initialize_pool(&mut s, subsidy_yes, subsidy_no, fee_bps) {
            prop_assert!(status_monotone(&s),
                "status_monotone must hold after initialize_pool");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn swap_yes_for_no_preserves_status_monotone(s in arb_state(), amount_in in 0u64..=u64::MAX, amount_out in 0u64..=u64::MAX, min_amount_out in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(swap_no_drain(&s));
        prop_assume!(fee_bps_bounded(&s));
        prop_assume!(status_monotone(&s));
        if swap_yes_for_no(&mut s, amount_in, amount_out, min_amount_out) {
            prop_assert!(status_monotone(&s),
                "status_monotone must hold after swap_yes_for_no");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn swap_no_for_yes_preserves_status_monotone(s in arb_state(), amount_in in 0u64..=u64::MAX, amount_out in 0u64..=u64::MAX, min_amount_out in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(swap_no_drain(&s));
        prop_assume!(fee_bps_bounded(&s));
        prop_assume!(status_monotone(&s));
        if swap_no_for_yes(&mut s, amount_in, amount_out, min_amount_out) {
            prop_assert!(status_monotone(&s),
                "status_monotone must hold after swap_no_for_yes");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn mark_resolved_yes_preserves_status_monotone(s in arb_state()) {
        let mut s = s;
        prop_assume!(swap_no_drain(&s));
        prop_assume!(fee_bps_bounded(&s));
        prop_assume!(status_monotone(&s));
        if mark_resolved_yes(&mut s) {
            prop_assert!(status_monotone(&s),
                "status_monotone must hold after mark_resolved_yes");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn mark_resolved_no_preserves_status_monotone(s in arb_state()) {
        let mut s = s;
        prop_assume!(swap_no_drain(&s));
        prop_assume!(fee_bps_bounded(&s));
        prop_assume!(status_monotone(&s));
        if mark_resolved_no(&mut s) {
            prop_assert!(status_monotone(&s),
                "status_monotone must hold after mark_resolved_no");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn withdraw_yes_after_resolution_preserves_status_monotone(s in arb_state(), amount in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(swap_no_drain(&s));
        prop_assume!(fee_bps_bounded(&s));
        prop_assume!(status_monotone(&s));
        if withdraw_yes_after_resolution(&mut s, amount) {
            prop_assert!(status_monotone(&s),
                "status_monotone must hold after withdraw_yes_after_resolution");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn withdraw_no_after_resolution_preserves_status_monotone(s in arb_state(), amount in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(swap_no_drain(&s));
        prop_assume!(fee_bps_bounded(&s));
        prop_assume!(status_monotone(&s));
        if withdraw_no_after_resolution(&mut s, amount) {
            prop_assert!(status_monotone(&s),
                "status_monotone must hold after withdraw_no_after_resolution");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn initialize_pool_rejects_invalid(s in arb_boundary_state(), subsidy_yes in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], subsidy_no in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], fee_bps in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX]) {
        let mut s = s;
        prop_assume!(!(s.initialized == 0 && subsidy_yes > 0 && subsidy_no > 0 && fee_bps <= 1000));
        prop_assert!(!initialize_pool(&mut s, subsidy_yes, subsidy_no, fee_bps),
            "initialize_pool must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn swap_yes_for_no_rejects_invalid(s in arb_boundary_state(), amount_in in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], amount_out in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], min_amount_out in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX]) {
        let mut s = s;
        prop_assume!(!(s.status == 0 && amount_in > 0 && amount_out >= min_amount_out && amount_out < s.no_reserves));
        prop_assert!(!swap_yes_for_no(&mut s, amount_in, amount_out, min_amount_out),
            "swap_yes_for_no must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn swap_no_for_yes_rejects_invalid(s in arb_boundary_state(), amount_in in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], amount_out in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], min_amount_out in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX]) {
        let mut s = s;
        prop_assume!(!(s.status == 0 && amount_in > 0 && amount_out >= min_amount_out && amount_out < s.yes_reserves));
        prop_assert!(!swap_no_for_yes(&mut s, amount_in, amount_out, min_amount_out),
            "swap_no_for_yes must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn mark_resolved_yes_rejects_invalid(s in arb_boundary_state()) {
        let mut s = s;
        prop_assume!(!(s.status == 0));
        prop_assert!(!mark_resolved_yes(&mut s),
            "mark_resolved_yes must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn mark_resolved_no_rejects_invalid(s in arb_boundary_state()) {
        let mut s = s;
        prop_assume!(!(s.status == 0));
        prop_assert!(!mark_resolved_no(&mut s),
            "mark_resolved_no must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn withdraw_yes_after_resolution_rejects_invalid(s in arb_boundary_state(), amount in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX]) {
        let mut s = s;
        prop_assume!(!(s.status == 1 && amount > 0 && amount <= s.yes_reserves));
        prop_assert!(!withdraw_yes_after_resolution(&mut s, amount),
            "withdraw_yes_after_resolution must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn withdraw_no_after_resolution_rejects_invalid(s in arb_boundary_state(), amount in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX]) {
        let mut s = s;
        prop_assume!(!(s.status == 2 && amount > 0 && amount <= s.no_reserves));
        prop_assert!(!withdraw_no_after_resolution(&mut s, amount),
            "withdraw_no_after_resolution must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn swap_yes_for_no_no_overflow_on_yes_reserves(s in arb_state(), amount_in in 0u64..=u64::MAX, amount_out in 0u64..=u64::MAX, min_amount_out in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(swap_no_drain(&s));
        prop_assume!(fee_bps_bounded(&s));
        prop_assume!(status_monotone(&s));
        let pre = s.yes_reserves;
        if swap_yes_for_no(&mut s, amount_in, amount_out, min_amount_out) {
            // If transition succeeded, the add must not have wrapped
            prop_assert!(s.yes_reserves >= pre,
                "overflow: swap_yes_for_no.yes_reserves wrapped around after add");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn swap_no_for_yes_no_overflow_on_no_reserves(s in arb_state(), amount_in in 0u64..=u64::MAX, amount_out in 0u64..=u64::MAX, min_amount_out in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(swap_no_drain(&s));
        prop_assume!(fee_bps_bounded(&s));
        prop_assume!(status_monotone(&s));
        let pre = s.no_reserves;
        if swap_no_for_yes(&mut s, amount_in, amount_out, min_amount_out) {
            // If transition succeeded, the add must not have wrapped
            prop_assert!(s.no_reserves >= pre,
                "overflow: swap_no_for_yes.no_reserves wrapped around after add");
        }
    }
}

#[derive(Debug, Clone)]
enum Op {
    InitializePool(u64, u64, u64),
    SwapYesForNo(u64, u64, u64),
    SwapNoForYes(u64, u64, u64),
    MarkResolvedYes,
    MarkResolvedNo,
    WithdrawYesAfterResolution(u64),
    WithdrawNoAfterResolution(u64),
}

fn arb_op() -> impl Strategy<Value = Op> {
    prop_oneof![
        (0u64..=u64::MAX, 0u64..=u64::MAX, 0u64..=u64::MAX).prop_map(|(subsidy_yes, subsidy_no, fee_bps)| Op::InitializePool(subsidy_yes, subsidy_no, fee_bps)),
        (0u64..=u64::MAX, 0u64..=u64::MAX, 0u64..=u64::MAX).prop_map(|(amount_in, amount_out, min_amount_out)| Op::SwapYesForNo(amount_in, amount_out, min_amount_out)),
        (0u64..=u64::MAX, 0u64..=u64::MAX, 0u64..=u64::MAX).prop_map(|(amount_in, amount_out, min_amount_out)| Op::SwapNoForYes(amount_in, amount_out, min_amount_out)),
        Just(Op::MarkResolvedYes),
        Just(Op::MarkResolvedNo),
        (0u64..=u64::MAX).prop_map(|v| Op::WithdrawYesAfterResolution(v)),
        (0u64..=u64::MAX).prop_map(|v| Op::WithdrawNoAfterResolution(v)),
    ]
}

fn apply_op(s: &mut State, op: &Op) -> bool {
    match op {
        Op::InitializePool(subsidy_yes, subsidy_no, fee_bps) => initialize_pool(s, *subsidy_yes, *subsidy_no, *fee_bps),
        Op::SwapYesForNo(amount_in, amount_out, min_amount_out) => swap_yes_for_no(s, *amount_in, *amount_out, *min_amount_out),
        Op::SwapNoForYes(amount_in, amount_out, min_amount_out) => swap_no_for_yes(s, *amount_in, *amount_out, *min_amount_out),
        Op::MarkResolvedYes => mark_resolved_yes(s),
        Op::MarkResolvedNo => mark_resolved_no(s),
        Op::WithdrawYesAfterResolution(amount) => withdraw_yes_after_resolution(s, *amount),
        Op::WithdrawNoAfterResolution(amount) => withdraw_no_after_resolution(s, *amount),
    }
}

fn assert_all_properties(s: &State, context: &str) {
    assert!(swap_no_drain(s), "{} violated: swap_no_drain", context);
    assert!(fee_bps_bounded(s), "{} violated: fee_bps_bounded", context);
    assert!(status_monotone(s), "{} violated: status_monotone", context);
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(256))]
    #[test]
    fn state_machine_sequence(ops in proptest::collection::vec(arb_op(), 1..20)) {
        let mut s = State {
        };
        for (i, op) in ops.iter().enumerate() {
            if apply_op(&mut s, op) {
                // Check all properties after each successful transition
                prop_assert!(swap_no_drain(&s),
                    "swap_no_drain violated after op {:?} (step {})", op, i);
                prop_assert!(fee_bps_bounded(&s),
                    "fee_bps_bounded violated after op {:?} (step {})", op, i);
                prop_assert!(status_monotone(&s),
                    "status_monotone violated after op {:?} (step {})", op, i);
            }
        }
    }
}
