// ---- GENERATED BY QEDGEN ---- spec-hash:56afe411b4f9532f
//
// Self-contained Kani proof harnesses for the spec.
//
// These proofs verify the spec's transition design using Kani bounded model
// checking. They operate on a pure model of the state machine (derived from
// the qedspec), independent of framework (Quasar/Anchor) types.
//
//   Lean proves:  transition functions preserve invariants (∀ states)
//   Kani checks:  same properties via bounded model checking + overflow detection
//   Together:     high assurance that the spec design is correct
//
// To run:  cargo kani --harness <name>   (requires cargo-kani)
// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
#![cfg(kani)]

// ============================================================================
// State model (derived from qedspec — no framework dependencies)
// ============================================================================

const STATUS_ACTIVE: u8 = 0;
const STATUS_RESOLVED_YES: u8 = 1;
const STATUS_RESOLVED_NO: u8 = 2;
const STATUS_RESOLVED_INVALID: u8 = 3;

#[derive(Clone, Copy, kani::Arbitrary)]
struct State {
    initialized: u8,
    status: u8,
    collateral_balance: u64,
    yes_supply: u64,
    no_supply: u64,
    vault: u64,
}

#[derive(Clone, Copy)]
struct State {
}

// ============================================================================
// Property predicates (from qedspec `property` declarations)
// ============================================================================

/// yes_no_paired_while_active: s.status ≠ 0 ∨ s.yes_supply = s.no_supply
fn yes_no_paired_while_active(s: &State) -> bool {
    (s.status != 0) || (s.yes_supply == s.no_supply)
}

/// vault_covers_supply: s.vault ≥ s.yes_supply ∨ s.vault ≥ s.no_supply
fn vault_covers_supply(s: &State) -> bool {
    (s.vault >= s.yes_supply) || (s.vault >= s.no_supply)
}

/// status_monotone: s.status ≤ 3
fn status_monotone(s: &State) -> bool {
    s.status <= 3
}

// ============================================================================
// Transition functions (from qedspec operations — effects + guards)
//
// Each returns true if the guard passes and the transition fires,
// false if the guard rejects the operation.
// ============================================================================

fn initialize_market(s: &mut State, initial_collateral: u64) -> bool {
    if !(s.initialized == 0) {
        return false;
    }
    s.initialized = 1;
    s.status = 0;
    s.collateral_balance = initial_collateral;
    s.yes_supply = 0;
    s.no_supply = 0;
    s.vault = 0;
    true
}

fn split(s: &mut State, amount: u64) -> bool {
    if !(s.initialized == 1 && s.status == 0 && amount > 0 && s.collateral_balance >= amount) {
        return false;
    }
    match s.collateral_balance.checked_sub(amount) {
        Some(__v) => s.collateral_balance = __v,
        None => return false,
    }
    match s.vault.checked_add(amount) {
        Some(__v) => s.vault = __v,
        None => return false,
    }
    match s.yes_supply.checked_add(amount) {
        Some(__v) => s.yes_supply = __v,
        None => return false,
    }
    match s.no_supply.checked_add(amount) {
        Some(__v) => s.no_supply = __v,
        None => return false,
    }
    true
}

fn merge(s: &mut State, amount: u64) -> bool {
    if !(s.initialized == 1 && s.status == 0 && amount > 0 && s.yes_supply >= amount && s.no_supply >= amount && s.vault >= amount) {
        return false;
    }
    match s.yes_supply.checked_sub(amount) {
        Some(__v) => s.yes_supply = __v,
        None => return false,
    }
    match s.no_supply.checked_sub(amount) {
        Some(__v) => s.no_supply = __v,
        None => return false,
    }
    match s.vault.checked_sub(amount) {
        Some(__v) => s.vault = __v,
        None => return false,
    }
    match s.collateral_balance.checked_add(amount) {
        Some(__v) => s.collateral_balance = __v,
        None => return false,
    }
    true
}

fn resolve_yes(s: &mut State) -> bool {
    if !(s.initialized == 1 && s.status == 0) {
        return false;
    }
    s.status = 1;
    true
}

fn resolve_no(s: &mut State) -> bool {
    if !(s.initialized == 1 && s.status == 0) {
        return false;
    }
    s.status = 2;
    true
}

fn redeem_yes(s: &mut State, amount: u64) -> bool {
    if !(s.status == 1 && amount > 0 && s.yes_supply >= amount && s.vault >= amount) {
        return false;
    }
    match s.yes_supply.checked_sub(amount) {
        Some(__v) => s.yes_supply = __v,
        None => return false,
    }
    match s.vault.checked_sub(amount) {
        Some(__v) => s.vault = __v,
        None => return false,
    }
    match s.collateral_balance.checked_add(amount) {
        Some(__v) => s.collateral_balance = __v,
        None => return false,
    }
    true
}

fn redeem_no(s: &mut State, amount: u64) -> bool {
    if !(s.status == 2 && amount > 0 && s.no_supply >= amount && s.vault >= amount) {
        return false;
    }
    match s.no_supply.checked_sub(amount) {
        Some(__v) => s.no_supply = __v,
        None => return false,
    }
    match s.vault.checked_sub(amount) {
        Some(__v) => s.vault = __v,
        None => return false,
    }
    match s.collateral_balance.checked_add(amount) {
        Some(__v) => s.collateral_balance = __v,
        None => return false,
    }
    true
}

// ============================================================================
// Guard enforcement — transitions reject invalid inputs
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_market_rejects_invalid() {
    let mut s = State {
    };
    let initial_collateral: u64 = kani::any();
    kani::assume(!(s.initialized == 0));
    assert!(!initialize_market(&mut s, initial_collateral),
        "initialize_market must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_split_rejects_invalid() {
    let mut s = State {
    };
    let amount: u64 = kani::any();
    kani::assume(!(s.initialized == 1 && s.status == 0 && amount > 0 && s.collateral_balance >= amount));
    assert!(!split(&mut s, amount),
        "split must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_merge_rejects_invalid() {
    let mut s = State {
    };
    let amount: u64 = kani::any();
    kani::assume(!(s.initialized == 1 && s.status == 0 && amount > 0 && s.yes_supply >= amount && s.no_supply >= amount && s.vault >= amount));
    assert!(!merge(&mut s, amount),
        "merge must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_yes_rejects_invalid() {
    let mut s = State {
    };
    kani::assume(!(s.initialized == 1 && s.status == 0));
    assert!(!resolve_yes(&mut s),
        "resolve_yes must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_no_rejects_invalid() {
    let mut s = State {
    };
    kani::assume(!(s.initialized == 1 && s.status == 0));
    assert!(!resolve_no(&mut s),
        "resolve_no must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_redeem_yes_rejects_invalid() {
    let mut s = State {
    };
    let amount: u64 = kani::any();
    kani::assume(!(s.status == 1 && amount > 0 && s.yes_supply >= amount && s.vault >= amount));
    assert!(!redeem_yes(&mut s, amount),
        "redeem_yes must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_redeem_no_rejects_invalid() {
    let mut s = State {
    };
    let amount: u64 = kani::any();
    kani::assume(!(s.status == 2 && amount > 0 && s.no_supply >= amount && s.vault >= amount));
    assert!(!redeem_no(&mut s, amount),
        "redeem_no must reject when guard is violated");
}

// ============================================================================
// Property preservation — invariants hold through all transitions
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_market_preserves_yes_no_paired_while_active() {
    let mut s = State {
    };
    kani::assume(yes_no_paired_while_active(&s));
    kani::assume(vault_covers_supply(&s));
    kani::assume(status_monotone(&s));
    let initial_collateral: u64 = kani::any();
    if initialize_market(&mut s, initial_collateral) {
        assert!(yes_no_paired_while_active(&s),
            "yes_no_paired_while_active must hold after initialize_market");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_split_preserves_yes_no_paired_while_active() {
    let mut s = State {
    };
    kani::assume(yes_no_paired_while_active(&s));
    kani::assume(vault_covers_supply(&s));
    kani::assume(status_monotone(&s));
    let amount: u64 = kani::any();
    if split(&mut s, amount) {
        assert!(yes_no_paired_while_active(&s),
            "yes_no_paired_while_active must hold after split");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_merge_preserves_yes_no_paired_while_active() {
    let mut s = State {
    };
    kani::assume(yes_no_paired_while_active(&s));
    kani::assume(vault_covers_supply(&s));
    kani::assume(status_monotone(&s));
    let amount: u64 = kani::any();
    if merge(&mut s, amount) {
        assert!(yes_no_paired_while_active(&s),
            "yes_no_paired_while_active must hold after merge");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_yes_preserves_yes_no_paired_while_active() {
    let mut s = State {
    };
    kani::assume(yes_no_paired_while_active(&s));
    kani::assume(vault_covers_supply(&s));
    kani::assume(status_monotone(&s));
    if resolve_yes(&mut s) {
        assert!(yes_no_paired_while_active(&s),
            "yes_no_paired_while_active must hold after resolve_yes");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_no_preserves_yes_no_paired_while_active() {
    let mut s = State {
    };
    kani::assume(yes_no_paired_while_active(&s));
    kani::assume(vault_covers_supply(&s));
    kani::assume(status_monotone(&s));
    if resolve_no(&mut s) {
        assert!(yes_no_paired_while_active(&s),
            "yes_no_paired_while_active must hold after resolve_no");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_redeem_yes_preserves_yes_no_paired_while_active() {
    let mut s = State {
    };
    kani::assume(yes_no_paired_while_active(&s));
    kani::assume(vault_covers_supply(&s));
    kani::assume(status_monotone(&s));
    let amount: u64 = kani::any();
    if redeem_yes(&mut s, amount) {
        assert!(yes_no_paired_while_active(&s),
            "yes_no_paired_while_active must hold after redeem_yes");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_redeem_no_preserves_yes_no_paired_while_active() {
    let mut s = State {
    };
    kani::assume(yes_no_paired_while_active(&s));
    kani::assume(vault_covers_supply(&s));
    kani::assume(status_monotone(&s));
    let amount: u64 = kani::any();
    if redeem_no(&mut s, amount) {
        assert!(yes_no_paired_while_active(&s),
            "yes_no_paired_while_active must hold after redeem_no");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_market_preserves_vault_covers_supply() {
    let mut s = State {
    };
    kani::assume(yes_no_paired_while_active(&s));
    kani::assume(vault_covers_supply(&s));
    kani::assume(status_monotone(&s));
    let initial_collateral: u64 = kani::any();
    if initialize_market(&mut s, initial_collateral) {
        assert!(vault_covers_supply(&s),
            "vault_covers_supply must hold after initialize_market");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_split_preserves_vault_covers_supply() {
    let mut s = State {
    };
    kani::assume(yes_no_paired_while_active(&s));
    kani::assume(vault_covers_supply(&s));
    kani::assume(status_monotone(&s));
    let amount: u64 = kani::any();
    if split(&mut s, amount) {
        assert!(vault_covers_supply(&s),
            "vault_covers_supply must hold after split");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_merge_preserves_vault_covers_supply() {
    let mut s = State {
    };
    kani::assume(yes_no_paired_while_active(&s));
    kani::assume(vault_covers_supply(&s));
    kani::assume(status_monotone(&s));
    let amount: u64 = kani::any();
    if merge(&mut s, amount) {
        assert!(vault_covers_supply(&s),
            "vault_covers_supply must hold after merge");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_yes_preserves_vault_covers_supply() {
    let mut s = State {
    };
    kani::assume(yes_no_paired_while_active(&s));
    kani::assume(vault_covers_supply(&s));
    kani::assume(status_monotone(&s));
    if resolve_yes(&mut s) {
        assert!(vault_covers_supply(&s),
            "vault_covers_supply must hold after resolve_yes");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_no_preserves_vault_covers_supply() {
    let mut s = State {
    };
    kani::assume(yes_no_paired_while_active(&s));
    kani::assume(vault_covers_supply(&s));
    kani::assume(status_monotone(&s));
    if resolve_no(&mut s) {
        assert!(vault_covers_supply(&s),
            "vault_covers_supply must hold after resolve_no");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_redeem_yes_preserves_vault_covers_supply() {
    let mut s = State {
    };
    kani::assume(yes_no_paired_while_active(&s));
    kani::assume(vault_covers_supply(&s));
    kani::assume(status_monotone(&s));
    let amount: u64 = kani::any();
    if redeem_yes(&mut s, amount) {
        assert!(vault_covers_supply(&s),
            "vault_covers_supply must hold after redeem_yes");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_redeem_no_preserves_vault_covers_supply() {
    let mut s = State {
    };
    kani::assume(yes_no_paired_while_active(&s));
    kani::assume(vault_covers_supply(&s));
    kani::assume(status_monotone(&s));
    let amount: u64 = kani::any();
    if redeem_no(&mut s, amount) {
        assert!(vault_covers_supply(&s),
            "vault_covers_supply must hold after redeem_no");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_market_preserves_status_monotone() {
    let mut s = State {
    };
    kani::assume(yes_no_paired_while_active(&s));
    kani::assume(vault_covers_supply(&s));
    kani::assume(status_monotone(&s));
    let initial_collateral: u64 = kani::any();
    if initialize_market(&mut s, initial_collateral) {
        assert!(status_monotone(&s),
            "status_monotone must hold after initialize_market");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_split_preserves_status_monotone() {
    let mut s = State {
    };
    kani::assume(yes_no_paired_while_active(&s));
    kani::assume(vault_covers_supply(&s));
    kani::assume(status_monotone(&s));
    let amount: u64 = kani::any();
    if split(&mut s, amount) {
        assert!(status_monotone(&s),
            "status_monotone must hold after split");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_merge_preserves_status_monotone() {
    let mut s = State {
    };
    kani::assume(yes_no_paired_while_active(&s));
    kani::assume(vault_covers_supply(&s));
    kani::assume(status_monotone(&s));
    let amount: u64 = kani::any();
    if merge(&mut s, amount) {
        assert!(status_monotone(&s),
            "status_monotone must hold after merge");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_yes_preserves_status_monotone() {
    let mut s = State {
    };
    kani::assume(yes_no_paired_while_active(&s));
    kani::assume(vault_covers_supply(&s));
    kani::assume(status_monotone(&s));
    if resolve_yes(&mut s) {
        assert!(status_monotone(&s),
            "status_monotone must hold after resolve_yes");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_no_preserves_status_monotone() {
    let mut s = State {
    };
    kani::assume(yes_no_paired_while_active(&s));
    kani::assume(vault_covers_supply(&s));
    kani::assume(status_monotone(&s));
    if resolve_no(&mut s) {
        assert!(status_monotone(&s),
            "status_monotone must hold after resolve_no");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_redeem_yes_preserves_status_monotone() {
    let mut s = State {
    };
    kani::assume(yes_no_paired_while_active(&s));
    kani::assume(vault_covers_supply(&s));
    kani::assume(status_monotone(&s));
    let amount: u64 = kani::any();
    if redeem_yes(&mut s, amount) {
        assert!(status_monotone(&s),
            "status_monotone must hold after redeem_yes");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_redeem_no_preserves_status_monotone() {
    let mut s = State {
    };
    kani::assume(yes_no_paired_while_active(&s));
    kani::assume(vault_covers_supply(&s));
    kani::assume(status_monotone(&s));
    let amount: u64 = kani::any();
    if redeem_no(&mut s, amount) {
        assert!(status_monotone(&s),
            "status_monotone must hold after redeem_no");
    }
}

// ============================================================================
// Effect conformance — verify transition effects match spec
//
// Each proof applies a transition to symbolic state and checks that every
// field changed/unchanged matches the spec's effect: declarations.
// ============================================================================

// ============================================================================
// Cover properties — reachability via kani::cover!
// ============================================================================

#[kani::proof]
#[kani::unwind(4)]
#[kani::solver(cadical)]
fn cover_split_merge_roundtrip() {
    let mut s = State {
    };
    let initial_collateral_0: u64 = kani::any();
    if initialize_market(&mut s, initial_collateral_0) {
        let amount_1: u64 = kani::any();
        if split(&mut s, amount_1) {
            let amount_2: u64 = kani::any();
            kani::cover!(merge(&mut s, amount_2), "split_merge_roundtrip trace is reachable");
        }
    }
}

#[kani::proof]
#[kani::unwind(5)]
#[kani::solver(cadical)]
fn cover_redeem_yes_path() {
    let mut s = State {
    };
    let initial_collateral_0: u64 = kani::any();
    if initialize_market(&mut s, initial_collateral_0) {
        let amount_1: u64 = kani::any();
        if split(&mut s, amount_1) {
            if resolve_yes(&mut s) {
                let amount_3: u64 = kani::any();
                kani::cover!(redeem_yes(&mut s, amount_3), "redeem_yes_path trace is reachable");
            }
        }
    }
}

#[kani::proof]
#[kani::unwind(5)]
#[kani::solver(cadical)]
fn cover_redeem_no_path() {
    let mut s = State {
    };
    let initial_collateral_0: u64 = kani::any();
    if initialize_market(&mut s, initial_collateral_0) {
        let amount_1: u64 = kani::any();
        if split(&mut s, amount_1) {
            if resolve_no(&mut s) {
                let amount_3: u64 = kani::any();
                kani::cover!(redeem_no(&mut s, amount_3), "redeem_no_path trace is reachable");
            }
        }
    }
}

// ============================================================================
// Overflow detection — Kani catches arithmetic overflow on add effects
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_split_no_overflow() {
    let mut s = State {
    };
    let amount: u64 = kani::any();
    split(&mut s, amount);  // Kani detects overflow on += internally
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_merge_no_overflow() {
    let mut s = State {
    };
    let amount: u64 = kani::any();
    merge(&mut s, amount);  // Kani detects overflow on += internally
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_redeem_yes_no_overflow() {
    let mut s = State {
    };
    let amount: u64 = kani::any();
    redeem_yes(&mut s, amount);  // Kani detects overflow on += internally
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_redeem_no_no_overflow() {
    let mut s = State {
    };
    let amount: u64 = kani::any();
    redeem_no(&mut s, amount);  // Kani detects overflow on += internally
}

// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
