// ---- GENERATED BY QEDGEN ----
//
// Proptest harnesses — property-based testing for the spec's state machine.
// Tier 1 of the verification waterfall: finds counterexamples in milliseconds.
//
//   Proptest: random testing, fast counterexamples (~100ms)
//   Kani:     bounded model checking, exhaustive within bounds (~5-30s)
//   Lean:     mathematical proof, universal guarantees (minutes-hours)
//
// To run:  cargo test --test proptest
// Deep:    PROPTEST_CASES=10000 cargo test --test proptest
// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----

use proptest::prelude::*;

const STATUS_ACTIVE: u8 = 0;
const STATUS_RESOLVED_YES: u8 = 1;
const STATUS_RESOLVED_NO: u8 = 2;
const STATUS_RESOLVED_INVALID: u8 = 3;

#[derive(Debug, Clone, Copy)]
struct State {
    initialized: u8,
    status: u8,
    collateral_balance: u64,
    yes_supply: u64,
    no_supply: u64,
    vault: u64,
}

prop_compose! {
    fn arb_State()(initialized in 0u8..=255u8, status in 0u8..=255u8, collateral_balance in 0u64..=u64::MAX, yes_supply in 0u64..=u64::MAX, no_supply in 0u64..=u64::MAX, vault in 0u64..=u64::MAX) -> State {
        State {
            initialized,
            status,
            collateral_balance,
            yes_supply,
            no_supply,
            vault,
        }
    }
}

#[derive(Debug, Clone, Copy)]
struct State {
}

/// Proptest strategy for generating arbitrary State values.
fn arb_state() -> impl Strategy<Value = State> {
    (
,
    ).prop_map(|()| State {
    })
}

/// Boundary-biased strategy for guard rejection tests.
fn arb_boundary_state() -> impl Strategy<Value = State> {
    (
,
    ).prop_map(|()| State {
    })
}

/// yes_no_paired_while_active: s.status ≠ 0 ∨ s.yes_supply = s.no_supply
fn yes_no_paired_while_active(s: &State) -> bool {
    (s.status != 0) || (s.yes_supply == s.no_supply)
}

/// vault_covers_supply: s.vault ≥ s.yes_supply ∨ s.vault ≥ s.no_supply
fn vault_covers_supply(s: &State) -> bool {
    (s.vault >= s.yes_supply) || (s.vault >= s.no_supply)
}

/// status_monotone: s.status ≤ 3
fn status_monotone(s: &State) -> bool {
    s.status <= 3
}

fn initialize_market(s: &mut State, initial_collateral: u64) -> bool {
    if !(s.initialized == 0) {
        return false;
    }
    s.initialized = 1;
    s.status = 0;
    s.collateral_balance = initial_collateral;
    s.yes_supply = 0;
    s.no_supply = 0;
    s.vault = 0;
    true
}

fn split(s: &mut State, amount: u64) -> bool {
    if !(s.initialized == 1 && s.status == 0 && amount > 0 && s.collateral_balance >= amount) {
        return false;
    }
    s.collateral_balance = s.collateral_balance.wrapping_sub(amount);
    s.vault = s.vault.wrapping_add(amount);
    s.yes_supply = s.yes_supply.wrapping_add(amount);
    s.no_supply = s.no_supply.wrapping_add(amount);
    true
}

fn merge(s: &mut State, amount: u64) -> bool {
    if !(s.initialized == 1 && s.status == 0 && amount > 0 && s.yes_supply >= amount && s.no_supply >= amount && s.vault >= amount) {
        return false;
    }
    s.yes_supply = s.yes_supply.wrapping_sub(amount);
    s.no_supply = s.no_supply.wrapping_sub(amount);
    s.vault = s.vault.wrapping_sub(amount);
    s.collateral_balance = s.collateral_balance.wrapping_add(amount);
    true
}

fn resolve_yes(s: &mut State) -> bool {
    if !(s.initialized == 1 && s.status == 0) {
        return false;
    }
    s.status = 1;
    true
}

fn resolve_no(s: &mut State) -> bool {
    if !(s.initialized == 1 && s.status == 0) {
        return false;
    }
    s.status = 2;
    true
}

fn redeem_yes(s: &mut State, amount: u64) -> bool {
    if !(s.status == 1 && amount > 0 && s.yes_supply >= amount && s.vault >= amount) {
        return false;
    }
    s.yes_supply = s.yes_supply.wrapping_sub(amount);
    s.vault = s.vault.wrapping_sub(amount);
    s.collateral_balance = s.collateral_balance.wrapping_add(amount);
    true
}

fn redeem_no(s: &mut State, amount: u64) -> bool {
    if !(s.status == 2 && amount > 0 && s.no_supply >= amount && s.vault >= amount) {
        return false;
    }
    s.no_supply = s.no_supply.wrapping_sub(amount);
    s.vault = s.vault.wrapping_sub(amount);
    s.collateral_balance = s.collateral_balance.wrapping_add(amount);
    true
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn initialize_market_preserves_yes_no_paired_while_active(s in arb_state(), initial_collateral in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        if initialize_market(&mut s, initial_collateral) {
            prop_assert!(yes_no_paired_while_active(&s),
                "yes_no_paired_while_active must hold after initialize_market");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn split_preserves_yes_no_paired_while_active(s in arb_state(), amount in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        if split(&mut s, amount) {
            prop_assert!(yes_no_paired_while_active(&s),
                "yes_no_paired_while_active must hold after split");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn merge_preserves_yes_no_paired_while_active(s in arb_state(), amount in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        if merge(&mut s, amount) {
            prop_assert!(yes_no_paired_while_active(&s),
                "yes_no_paired_while_active must hold after merge");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_yes_preserves_yes_no_paired_while_active(s in arb_state()) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        if resolve_yes(&mut s) {
            prop_assert!(yes_no_paired_while_active(&s),
                "yes_no_paired_while_active must hold after resolve_yes");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_no_preserves_yes_no_paired_while_active(s in arb_state()) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        if resolve_no(&mut s) {
            prop_assert!(yes_no_paired_while_active(&s),
                "yes_no_paired_while_active must hold after resolve_no");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn redeem_yes_preserves_yes_no_paired_while_active(s in arb_state(), amount in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        if redeem_yes(&mut s, amount) {
            prop_assert!(yes_no_paired_while_active(&s),
                "yes_no_paired_while_active must hold after redeem_yes");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn redeem_no_preserves_yes_no_paired_while_active(s in arb_state(), amount in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        if redeem_no(&mut s, amount) {
            prop_assert!(yes_no_paired_while_active(&s),
                "yes_no_paired_while_active must hold after redeem_no");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn initialize_market_preserves_vault_covers_supply(s in arb_state(), initial_collateral in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        if initialize_market(&mut s, initial_collateral) {
            prop_assert!(vault_covers_supply(&s),
                "vault_covers_supply must hold after initialize_market");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn split_preserves_vault_covers_supply(s in arb_state(), amount in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        if split(&mut s, amount) {
            prop_assert!(vault_covers_supply(&s),
                "vault_covers_supply must hold after split");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn merge_preserves_vault_covers_supply(s in arb_state(), amount in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        if merge(&mut s, amount) {
            prop_assert!(vault_covers_supply(&s),
                "vault_covers_supply must hold after merge");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_yes_preserves_vault_covers_supply(s in arb_state()) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        if resolve_yes(&mut s) {
            prop_assert!(vault_covers_supply(&s),
                "vault_covers_supply must hold after resolve_yes");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_no_preserves_vault_covers_supply(s in arb_state()) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        if resolve_no(&mut s) {
            prop_assert!(vault_covers_supply(&s),
                "vault_covers_supply must hold after resolve_no");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn redeem_yes_preserves_vault_covers_supply(s in arb_state(), amount in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        if redeem_yes(&mut s, amount) {
            prop_assert!(vault_covers_supply(&s),
                "vault_covers_supply must hold after redeem_yes");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn redeem_no_preserves_vault_covers_supply(s in arb_state(), amount in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        if redeem_no(&mut s, amount) {
            prop_assert!(vault_covers_supply(&s),
                "vault_covers_supply must hold after redeem_no");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn initialize_market_preserves_status_monotone(s in arb_state(), initial_collateral in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        if initialize_market(&mut s, initial_collateral) {
            prop_assert!(status_monotone(&s),
                "status_monotone must hold after initialize_market");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn split_preserves_status_monotone(s in arb_state(), amount in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        if split(&mut s, amount) {
            prop_assert!(status_monotone(&s),
                "status_monotone must hold after split");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn merge_preserves_status_monotone(s in arb_state(), amount in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        if merge(&mut s, amount) {
            prop_assert!(status_monotone(&s),
                "status_monotone must hold after merge");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_yes_preserves_status_monotone(s in arb_state()) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        if resolve_yes(&mut s) {
            prop_assert!(status_monotone(&s),
                "status_monotone must hold after resolve_yes");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_no_preserves_status_monotone(s in arb_state()) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        if resolve_no(&mut s) {
            prop_assert!(status_monotone(&s),
                "status_monotone must hold after resolve_no");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn redeem_yes_preserves_status_monotone(s in arb_state(), amount in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        if redeem_yes(&mut s, amount) {
            prop_assert!(status_monotone(&s),
                "status_monotone must hold after redeem_yes");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn redeem_no_preserves_status_monotone(s in arb_state(), amount in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        if redeem_no(&mut s, amount) {
            prop_assert!(status_monotone(&s),
                "status_monotone must hold after redeem_no");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn initialize_market_rejects_invalid(s in arb_boundary_state(), initial_collateral in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX]) {
        let mut s = s;
        prop_assume!(!(s.initialized == 0));
        prop_assert!(!initialize_market(&mut s, initial_collateral),
            "initialize_market must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn split_rejects_invalid(s in arb_boundary_state(), amount in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX]) {
        let mut s = s;
        prop_assume!(!(s.initialized == 1 && s.status == 0 && amount > 0 && s.collateral_balance >= amount));
        prop_assert!(!split(&mut s, amount),
            "split must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn merge_rejects_invalid(s in arb_boundary_state(), amount in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX]) {
        let mut s = s;
        prop_assume!(!(s.initialized == 1 && s.status == 0 && amount > 0 && s.yes_supply >= amount && s.no_supply >= amount && s.vault >= amount));
        prop_assert!(!merge(&mut s, amount),
            "merge must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_yes_rejects_invalid(s in arb_boundary_state()) {
        let mut s = s;
        prop_assume!(!(s.initialized == 1 && s.status == 0));
        prop_assert!(!resolve_yes(&mut s),
            "resolve_yes must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_no_rejects_invalid(s in arb_boundary_state()) {
        let mut s = s;
        prop_assume!(!(s.initialized == 1 && s.status == 0));
        prop_assert!(!resolve_no(&mut s),
            "resolve_no must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn redeem_yes_rejects_invalid(s in arb_boundary_state(), amount in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX]) {
        let mut s = s;
        prop_assume!(!(s.status == 1 && amount > 0 && s.yes_supply >= amount && s.vault >= amount));
        prop_assert!(!redeem_yes(&mut s, amount),
            "redeem_yes must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn redeem_no_rejects_invalid(s in arb_boundary_state(), amount in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX]) {
        let mut s = s;
        prop_assume!(!(s.status == 2 && amount > 0 && s.no_supply >= amount && s.vault >= amount));
        prop_assert!(!redeem_no(&mut s, amount),
            "redeem_no must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn split_no_overflow_on_vault(s in arb_state(), amount in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        let pre = s.vault;
        if split(&mut s, amount) {
            // If transition succeeded, the add must not have wrapped
            prop_assert!(s.vault >= pre,
                "overflow: split.vault wrapped around after add");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn split_no_overflow_on_yes_supply(s in arb_state(), amount in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        let pre = s.yes_supply;
        if split(&mut s, amount) {
            // If transition succeeded, the add must not have wrapped
            prop_assert!(s.yes_supply >= pre,
                "overflow: split.yes_supply wrapped around after add");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn split_no_overflow_on_no_supply(s in arb_state(), amount in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        let pre = s.no_supply;
        if split(&mut s, amount) {
            // If transition succeeded, the add must not have wrapped
            prop_assert!(s.no_supply >= pre,
                "overflow: split.no_supply wrapped around after add");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn merge_no_overflow_on_collateral_balance(s in arb_state(), amount in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        let pre = s.collateral_balance;
        if merge(&mut s, amount) {
            // If transition succeeded, the add must not have wrapped
            prop_assert!(s.collateral_balance >= pre,
                "overflow: merge.collateral_balance wrapped around after add");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn redeem_yes_no_overflow_on_collateral_balance(s in arb_state(), amount in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        let pre = s.collateral_balance;
        if redeem_yes(&mut s, amount) {
            // If transition succeeded, the add must not have wrapped
            prop_assert!(s.collateral_balance >= pre,
                "overflow: redeem_yes.collateral_balance wrapped around after add");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn redeem_no_no_overflow_on_collateral_balance(s in arb_state(), amount in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(yes_no_paired_while_active(&s));
        prop_assume!(vault_covers_supply(&s));
        prop_assume!(status_monotone(&s));
        let pre = s.collateral_balance;
        if redeem_no(&mut s, amount) {
            // If transition succeeded, the add must not have wrapped
            prop_assert!(s.collateral_balance >= pre,
                "overflow: redeem_no.collateral_balance wrapped around after add");
        }
    }
}

#[derive(Debug, Clone)]
enum Op {
    InitializeMarket(u64),
    Split(u64),
    Merge(u64),
    ResolveYes,
    ResolveNo,
    RedeemYes(u64),
    RedeemNo(u64),
}

fn arb_op() -> impl Strategy<Value = Op> {
    prop_oneof![
        (0u64..=u64::MAX).prop_map(|v| Op::InitializeMarket(v)),
        (0u64..=u64::MAX).prop_map(|v| Op::Split(v)),
        (0u64..=u64::MAX).prop_map(|v| Op::Merge(v)),
        Just(Op::ResolveYes),
        Just(Op::ResolveNo),
        (0u64..=u64::MAX).prop_map(|v| Op::RedeemYes(v)),
        (0u64..=u64::MAX).prop_map(|v| Op::RedeemNo(v)),
    ]
}

fn apply_op(s: &mut State, op: &Op) -> bool {
    match op {
        Op::InitializeMarket(initial_collateral) => initialize_market(s, *initial_collateral),
        Op::Split(amount) => split(s, *amount),
        Op::Merge(amount) => merge(s, *amount),
        Op::ResolveYes => resolve_yes(s),
        Op::ResolveNo => resolve_no(s),
        Op::RedeemYes(amount) => redeem_yes(s, *amount),
        Op::RedeemNo(amount) => redeem_no(s, *amount),
    }
}

fn assert_all_properties(s: &State, context: &str) {
    assert!(yes_no_paired_while_active(s), "{} violated: yes_no_paired_while_active", context);
    assert!(vault_covers_supply(s), "{} violated: vault_covers_supply", context);
    assert!(status_monotone(s), "{} violated: status_monotone", context);
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(256))]
    #[test]
    fn state_machine_sequence(ops in proptest::collection::vec(arb_op(), 1..20)) {
        let mut s = State {
        };
        for (i, op) in ops.iter().enumerate() {
            if apply_op(&mut s, op) {
                // Check all properties after each successful transition
                prop_assert!(yes_no_paired_while_active(&s),
                    "yes_no_paired_while_active violated after op {:?} (step {})", op, i);
                prop_assert!(vault_covers_supply(&s),
                    "vault_covers_supply violated after op {:?} (step {})", op, i);
                prop_assert!(status_monotone(&s),
                    "status_monotone violated after op {:?} (step {})", op, i);
            }
        }
    }
}
