// ---- GENERATED BY QEDGEN ---- spec-hash:24f5d8722f56ac41
//
// Self-contained Kani proof harnesses for the spec.
//
// These proofs verify the spec's transition design using Kani bounded model
// checking. They operate on a pure model of the state machine (derived from
// the qedspec), independent of framework (Quasar/Anchor) types.
//
//   Lean proves:  transition functions preserve invariants (∀ states)
//   Kani checks:  same properties via bounded model checking + overflow detection
//   Together:     high assurance that the spec design is correct
//
// To run:  cargo kani --harness <name>   (requires cargo-kani)
// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
#![cfg(kani)]

// ============================================================================
// State model (derived from qedspec — no framework dependencies)
// ============================================================================

const OUTCOME_UNRESOLVED: u8 = 0;
const OUTCOME_YES: u8 = 1;
const OUTCOME_NO: u8 = 2;
const OUTCOME_INVALID: u8 = 3;

#[derive(Clone, Copy, kani::Arbitrary)]
struct State {
    initialized: u8,
    target_slot: u64,
    outcome_at_or_after: u8,
    last_returned: u8,
}

#[derive(Clone, Copy)]
struct State {
}

// ============================================================================
// Property predicates (from qedspec `property` declarations)
// ============================================================================

/// returned_value_bounded: s.last_returned = 0 ∨ s.last_returned = s.outcome_at_or_after
fn returned_value_bounded(s: &State) -> bool {
    (s.last_returned == 0) || (s.last_returned == s.outcome_at_or_after)
}

/// outcome_terminal_after_init: s.initialized = 0 ∨ (s.outcome_at_or_after ≥ 1 ∧ s.outcome_at_or_after ≤ 3)
fn outcome_terminal_after_init(s: &State) -> bool {
    (s.initialized == 0) || (((s.outcome_at_or_after >= 1) && (s.outcome_at_or_after <= 3)))
}

// ============================================================================
// Transition functions (from qedspec operations — effects + guards)
//
// Each returns true if the guard passes and the transition fires,
// false if the guard rejects the operation.
// ============================================================================

fn initialize(s: &mut State, target_slot: u64, outcome: u8) -> bool {
    if !(s.initialized == 0 && outcome >= 1 && outcome <= 3) {
        return false;
    }
    s.initialized = 1;
    s.target_slot = target_slot;
    s.outcome_at_or_after = outcome;
    true
}

fn resolve_case_0(s: &mut State, clock_slot: u64) -> bool {
    if !(clock_slot < s.target_slot) {
        return false;
    }
    s.last_returned = 0;
    true
}

fn resolve_otherwise(s: &mut State, clock_slot: u64) -> bool {
    if !(!(clock_slot < s.target_slot)) {
        return false;
    }
    s.last_returned = outcome_at_or_after;
    true
}

// ============================================================================
// Guard enforcement — transitions reject invalid inputs
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_rejects_invalid() {
    let mut s = State {
    };
    let target_slot: u64 = kani::any();
    let outcome: u8 = kani::any();
    kani::assume(!(s.initialized == 0 && outcome >= 1 && outcome <= 3));
    assert!(!initialize(&mut s, target_slot, outcome),
        "initialize must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_case_0_rejects_invalid() {
    let mut s = State {
    };
    let clock_slot: u64 = kani::any();
    kani::assume(!(clock_slot < s.target_slot));
    assert!(!resolve_case_0(&mut s, clock_slot),
        "resolve_case_0 must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_otherwise_rejects_invalid() {
    let mut s = State {
    };
    let clock_slot: u64 = kani::any();
    kani::assume(!(!(clock_slot < s.target_slot)));
    assert!(!resolve_otherwise(&mut s, clock_slot),
        "resolve_otherwise must reject when guard is violated");
}

// ============================================================================
// Property preservation — invariants hold through all transitions
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_preserves_returned_value_bounded() {
    let mut s = State {
    };
    kani::assume(returned_value_bounded(&s));
    kani::assume(outcome_terminal_after_init(&s));
    let target_slot: u64 = kani::any();
    let outcome: u8 = kani::any();
    if initialize(&mut s, target_slot, outcome) {
        assert!(returned_value_bounded(&s),
            "returned_value_bounded must hold after initialize");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_case_0_preserves_returned_value_bounded() {
    let mut s = State {
    };
    kani::assume(returned_value_bounded(&s));
    kani::assume(outcome_terminal_after_init(&s));
    let clock_slot: u64 = kani::any();
    if resolve_case_0(&mut s, clock_slot) {
        assert!(returned_value_bounded(&s),
            "returned_value_bounded must hold after resolve_case_0");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_otherwise_preserves_returned_value_bounded() {
    let mut s = State {
    };
    kani::assume(returned_value_bounded(&s));
    kani::assume(outcome_terminal_after_init(&s));
    let clock_slot: u64 = kani::any();
    if resolve_otherwise(&mut s, clock_slot) {
        assert!(returned_value_bounded(&s),
            "returned_value_bounded must hold after resolve_otherwise");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_preserves_outcome_terminal_after_init() {
    let mut s = State {
    };
    kani::assume(returned_value_bounded(&s));
    kani::assume(outcome_terminal_after_init(&s));
    let target_slot: u64 = kani::any();
    let outcome: u8 = kani::any();
    if initialize(&mut s, target_slot, outcome) {
        assert!(outcome_terminal_after_init(&s),
            "outcome_terminal_after_init must hold after initialize");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_case_0_preserves_outcome_terminal_after_init() {
    let mut s = State {
    };
    kani::assume(returned_value_bounded(&s));
    kani::assume(outcome_terminal_after_init(&s));
    let clock_slot: u64 = kani::any();
    if resolve_case_0(&mut s, clock_slot) {
        assert!(outcome_terminal_after_init(&s),
            "outcome_terminal_after_init must hold after resolve_case_0");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_otherwise_preserves_outcome_terminal_after_init() {
    let mut s = State {
    };
    kani::assume(returned_value_bounded(&s));
    kani::assume(outcome_terminal_after_init(&s));
    let clock_slot: u64 = kani::any();
    if resolve_otherwise(&mut s, clock_slot) {
        assert!(outcome_terminal_after_init(&s),
            "outcome_terminal_after_init must hold after resolve_otherwise");
    }
}

// ============================================================================
// Effect conformance — verify transition effects match spec
//
// Each proof applies a transition to symbolic state and checks that every
// field changed/unchanged matches the spec's effect: declarations.
// ============================================================================

// ============================================================================
// Cover properties — reachability via kani::cover!
// ============================================================================

#[kani::proof]
#[kani::unwind(3)]
#[kani::solver(cadical)]
fn cover_happy_path() {
    let mut s = State {
    };
    let target_slot_0: u64 = kani::any();
    let outcome_0: u8 = kani::any();
    if initialize(&mut s, target_slot_0, outcome_0) {
        kani::cover!(resolve(&mut s), "happy_path trace is reachable");
    }
}

// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
