// ---- GENERATED BY QEDGEN ----
//
// Proptest harnesses — property-based testing for the spec's state machine.
// Tier 1 of the verification waterfall: finds counterexamples in milliseconds.
//
//   Proptest: random testing, fast counterexamples (~100ms)
//   Kani:     bounded model checking, exhaustive within bounds (~5-30s)
//   Lean:     mathematical proof, universal guarantees (minutes-hours)
//
// To run:  cargo test --test proptest
// Deep:    PROPTEST_CASES=10000 cargo test --test proptest
// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----

use proptest::prelude::*;

const OUTCOME_UNRESOLVED: u8 = 0;
const OUTCOME_YES: u8 = 1;
const OUTCOME_NO: u8 = 2;
const OUTCOME_INVALID: u8 = 3;

#[derive(Debug, Clone, Copy)]
struct State {
    initialized: u8,
    target_slot: u64,
    outcome_at_or_after: u8,
    last_returned: u8,
}

prop_compose! {
    fn arb_State()(initialized in 0u8..=255u8, target_slot in 0u64..=u64::MAX, outcome_at_or_after in 0u8..=255u8, last_returned in 0u8..=255u8) -> State {
        State {
            initialized,
            target_slot,
            outcome_at_or_after,
            last_returned,
        }
    }
}

#[derive(Debug, Clone, Copy)]
struct State {
}

/// Proptest strategy for generating arbitrary State values.
fn arb_state() -> impl Strategy<Value = State> {
    (
,
    ).prop_map(|()| State {
    })
}

/// Boundary-biased strategy for guard rejection tests.
fn arb_boundary_state() -> impl Strategy<Value = State> {
    (
,
    ).prop_map(|()| State {
    })
}

/// returned_value_bounded: s.last_returned = 0 ∨ s.last_returned = s.outcome_at_or_after
fn returned_value_bounded(s: &State) -> bool {
    (s.last_returned == 0) || (s.last_returned == s.outcome_at_or_after)
}

/// outcome_terminal_after_init: s.initialized = 0 ∨ (s.outcome_at_or_after ≥ 1 ∧ s.outcome_at_or_after ≤ 3)
fn outcome_terminal_after_init(s: &State) -> bool {
    (s.initialized == 0) || (((s.outcome_at_or_after >= 1) && (s.outcome_at_or_after <= 3)))
}

fn initialize(s: &mut State, target_slot: u64, outcome: u8) -> bool {
    if !(s.initialized == 0 && outcome >= 1 && outcome <= 3) {
        return false;
    }
    s.initialized = 1;
    s.target_slot = target_slot;
    s.outcome_at_or_after = outcome;
    true
}

fn resolve_case_0(s: &mut State, clock_slot: u64) -> bool {
    if !(clock_slot < s.target_slot) {
        return false;
    }
    s.last_returned = 0;
    true
}

fn resolve_otherwise(s: &mut State, clock_slot: u64) -> bool {
    if !(!(clock_slot < s.target_slot)) {
        return false;
    }
    s.last_returned = outcome_at_or_after;
    true
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn initialize_preserves_returned_value_bounded(s in arb_state(), target_slot in 0u64..=u64::MAX, outcome in 0u8..=u8::MAX) {
        let mut s = s;
        prop_assume!(returned_value_bounded(&s));
        prop_assume!(outcome_terminal_after_init(&s));
        if initialize(&mut s, target_slot, outcome) {
            prop_assert!(returned_value_bounded(&s),
                "returned_value_bounded must hold after initialize");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_case_0_preserves_returned_value_bounded(s in arb_state(), clock_slot in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(returned_value_bounded(&s));
        prop_assume!(outcome_terminal_after_init(&s));
        if resolve_case_0(&mut s, clock_slot) {
            prop_assert!(returned_value_bounded(&s),
                "returned_value_bounded must hold after resolve_case_0");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_otherwise_preserves_returned_value_bounded(s in arb_state(), clock_slot in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(returned_value_bounded(&s));
        prop_assume!(outcome_terminal_after_init(&s));
        if resolve_otherwise(&mut s, clock_slot) {
            prop_assert!(returned_value_bounded(&s),
                "returned_value_bounded must hold after resolve_otherwise");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn initialize_preserves_outcome_terminal_after_init(s in arb_state(), target_slot in 0u64..=u64::MAX, outcome in 0u8..=u8::MAX) {
        let mut s = s;
        prop_assume!(returned_value_bounded(&s));
        prop_assume!(outcome_terminal_after_init(&s));
        if initialize(&mut s, target_slot, outcome) {
            prop_assert!(outcome_terminal_after_init(&s),
                "outcome_terminal_after_init must hold after initialize");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_case_0_preserves_outcome_terminal_after_init(s in arb_state(), clock_slot in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(returned_value_bounded(&s));
        prop_assume!(outcome_terminal_after_init(&s));
        if resolve_case_0(&mut s, clock_slot) {
            prop_assert!(outcome_terminal_after_init(&s),
                "outcome_terminal_after_init must hold after resolve_case_0");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_otherwise_preserves_outcome_terminal_after_init(s in arb_state(), clock_slot in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(returned_value_bounded(&s));
        prop_assume!(outcome_terminal_after_init(&s));
        if resolve_otherwise(&mut s, clock_slot) {
            prop_assert!(outcome_terminal_after_init(&s),
                "outcome_terminal_after_init must hold after resolve_otherwise");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn initialize_rejects_invalid(s in arb_boundary_state(), target_slot in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], outcome in prop_oneof![0u8..=3u8, 252u8..=255u8]) {
        let mut s = s;
        prop_assume!(!(s.initialized == 0 && outcome >= 1 && outcome <= 3));
        prop_assert!(!initialize(&mut s, target_slot, outcome),
            "initialize must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_case_0_rejects_invalid(s in arb_boundary_state(), clock_slot in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX]) {
        let mut s = s;
        prop_assume!(!(clock_slot < s.target_slot));
        prop_assert!(!resolve_case_0(&mut s, clock_slot),
            "resolve_case_0 must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_otherwise_rejects_invalid(s in arb_boundary_state(), clock_slot in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX]) {
        let mut s = s;
        prop_assume!(!(!(clock_slot < s.target_slot)));
        prop_assert!(!resolve_otherwise(&mut s, clock_slot),
            "resolve_otherwise must reject when guard is violated");
    }
}

#[derive(Debug, Clone)]
enum Op {
    Initialize(u64, u8),
    ResolveCase0(u64),
    ResolveOtherwise(u64),
}

fn arb_op() -> impl Strategy<Value = Op> {
    prop_oneof![
        (0u64..=u64::MAX, 0u8..=u8::MAX).prop_map(|(target_slot, outcome)| Op::Initialize(target_slot, outcome)),
        (0u64..=u64::MAX).prop_map(|v| Op::ResolveCase0(v)),
        (0u64..=u64::MAX).prop_map(|v| Op::ResolveOtherwise(v)),
    ]
}

fn apply_op(s: &mut State, op: &Op) -> bool {
    match op {
        Op::Initialize(target_slot, outcome) => initialize(s, *target_slot, *outcome),
        Op::ResolveCase0(clock_slot) => resolve_case_0(s, *clock_slot),
        Op::ResolveOtherwise(clock_slot) => resolve_otherwise(s, *clock_slot),
    }
}

fn assert_all_properties(s: &State, context: &str) {
    assert!(returned_value_bounded(s), "{} violated: returned_value_bounded", context);
    assert!(outcome_terminal_after_init(s), "{} violated: outcome_terminal_after_init", context);
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(256))]
    #[test]
    fn state_machine_sequence(ops in proptest::collection::vec(arb_op(), 1..20)) {
        let mut s = State {
        };
        for (i, op) in ops.iter().enumerate() {
            if apply_op(&mut s, op) {
                // Check all properties after each successful transition
                prop_assert!(returned_value_bounded(&s),
                    "returned_value_bounded violated after op {:?} (step {})", op, i);
                prop_assert!(outcome_terminal_after_init(&s),
                    "outcome_terminal_after_init violated after op {:?} (step {})", op, i);
            }
        }
    }
}
