// ---- GENERATED BY QEDGEN ---- spec-hash:986d2504279fccaa
//
// Self-contained Kani proof harnesses for the spec.
//
// These proofs verify the spec's transition design using Kani bounded model
// checking. They operate on a pure model of the state machine (derived from
// the qedspec), independent of framework (Quasar/Anchor) types.
//
//   Lean proves:  transition functions preserve invariants (∀ states)
//   Kani checks:  same properties via bounded model checking + overflow detection
//   Together:     high assurance that the spec design is correct
//
// To run:  cargo kani --harness <name>   (requires cargo-kani)
// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----

// ============================================================================
// State model (derived from qedspec — no framework dependencies)
// ============================================================================

const COMPARISON_GTE: u8 = 0;
const COMPARISON_LT: u8 = 1;

#[derive(Clone, Copy, kani::Arbitrary)]
struct State {
    initialized: u8,
    earliest_slot: u64,
    threshold_price: u64,
    threshold_expo: u64,
    comparison: u8,
    last_returned: u8,
}

// ============================================================================
// Property predicates (from qedspec `property` declarations)
// ============================================================================

/// outcome_in_canonical_range: s.last_returned ≤ 3
fn outcome_in_canonical_range(s: &State) -> bool {
    s.last_returned <= 3
}

/// comparison_bounded: s.initialized = 0 ∨ (s.comparison = 0 ∨ s.comparison = 1)
fn comparison_bounded(s: &State) -> bool {
    (s.initialized == 0) || (((s.comparison == 0) || (s.comparison == 1)))
}

// ============================================================================
// Transition functions (from qedspec operations — effects + guards)
//
// Each returns true if the guard passes and the transition fires,
// false if the guard rejects the operation.
// ============================================================================

fn initialize(s: &mut State, earliest_slot: u64, threshold_price: u64, threshold_expo: u64, comparison: u8) -> bool {
    if !(s.initialized == 0 && comparison <= 1) {
        return false;
    }
    s.initialized = 1;
    s.earliest_slot = earliest_slot;
    s.threshold_price = threshold_price;
    s.threshold_expo = threshold_expo;
    s.comparison = comparison;
    true
}

fn resolve_case_0(s: &mut State, clock_slot: u64, feed_price: u64, feed_expo: u64) -> bool {
    if !(clock_slot < s.earliest_slot) {
        return false;
    }
    s.last_returned = 0;
    true
}

fn resolve_case_1(s: &mut State, clock_slot: u64, feed_price: u64, feed_expo: u64) -> bool {
    if !(!(clock_slot < s.earliest_slot) && feed_expo != s.threshold_expo) {
        return false;
    }
    s.last_returned = 3;
    true
}

fn resolve_case_2(s: &mut State, clock_slot: u64, feed_price: u64, feed_expo: u64) -> bool {
    if !(!(clock_slot < s.earliest_slot) && !(feed_expo != s.threshold_expo) && (s.comparison == 0) && (feed_price >= s.threshold_price)) {
        return false;
    }
    s.last_returned = 1;
    true
}

fn resolve_case_3(s: &mut State, clock_slot: u64, feed_price: u64, feed_expo: u64) -> bool {
    if !(!(clock_slot < s.earliest_slot) && !(feed_expo != s.threshold_expo) && !((s.comparison == 0) && (feed_price >= s.threshold_price)) && (s.comparison == 1) && (feed_price < s.threshold_price)) {
        return false;
    }
    s.last_returned = 1;
    true
}

fn resolve_otherwise(s: &mut State, clock_slot: u64, feed_price: u64, feed_expo: u64) -> bool {
    if !(!(clock_slot < s.earliest_slot) && !(feed_expo != s.threshold_expo) && !((s.comparison == 0) && (feed_price >= s.threshold_price)) && !((s.comparison == 1) && (feed_price < s.threshold_price))) {
        return false;
    }
    s.last_returned = 2;
    true
}

// ============================================================================
// Guard enforcement — transitions reject invalid inputs
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_rejects_invalid() {
    let mut s: State = kani::any();
    let earliest_slot: u64 = kani::any();
    let threshold_price: u64 = kani::any();
    let threshold_expo: u64 = kani::any();
    let comparison: u8 = kani::any();
    kani::assume(!(s.initialized == 0 && comparison <= 1));
    assert!(!initialize(&mut s, earliest_slot, threshold_price, threshold_expo, comparison),
        "initialize must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_case_0_rejects_invalid() {
    let mut s: State = kani::any();
    let clock_slot: u64 = kani::any();
    let feed_price: u64 = kani::any();
    let feed_expo: u64 = kani::any();
    kani::assume(!(clock_slot < s.earliest_slot));
    assert!(!resolve_case_0(&mut s, clock_slot, feed_price, feed_expo),
        "resolve_case_0 must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_case_1_rejects_invalid() {
    let mut s: State = kani::any();
    let clock_slot: u64 = kani::any();
    let feed_price: u64 = kani::any();
    let feed_expo: u64 = kani::any();
    kani::assume(!(!(clock_slot < s.earliest_slot) && feed_expo != s.threshold_expo));
    assert!(!resolve_case_1(&mut s, clock_slot, feed_price, feed_expo),
        "resolve_case_1 must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_case_2_rejects_invalid() {
    let mut s: State = kani::any();
    let clock_slot: u64 = kani::any();
    let feed_price: u64 = kani::any();
    let feed_expo: u64 = kani::any();
    kani::assume(!(!(clock_slot < s.earliest_slot) && !(feed_expo != s.threshold_expo) && (s.comparison == 0) && (feed_price >= s.threshold_price)));
    assert!(!resolve_case_2(&mut s, clock_slot, feed_price, feed_expo),
        "resolve_case_2 must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_case_3_rejects_invalid() {
    let mut s: State = kani::any();
    let clock_slot: u64 = kani::any();
    let feed_price: u64 = kani::any();
    let feed_expo: u64 = kani::any();
    kani::assume(!(!(clock_slot < s.earliest_slot) && !(feed_expo != s.threshold_expo) && !((s.comparison == 0) && (feed_price >= s.threshold_price)) && (s.comparison == 1) && (feed_price < s.threshold_price)));
    assert!(!resolve_case_3(&mut s, clock_slot, feed_price, feed_expo),
        "resolve_case_3 must reject when guard is violated");
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_otherwise_rejects_invalid() {
    let mut s: State = kani::any();
    let clock_slot: u64 = kani::any();
    let feed_price: u64 = kani::any();
    let feed_expo: u64 = kani::any();
    kani::assume(!(!(clock_slot < s.earliest_slot) && !(feed_expo != s.threshold_expo) && !((s.comparison == 0) && (feed_price >= s.threshold_price)) && !((s.comparison == 1) && (feed_price < s.threshold_price))));
    assert!(!resolve_otherwise(&mut s, clock_slot, feed_price, feed_expo),
        "resolve_otherwise must reject when guard is violated");
}

// ============================================================================
// Property preservation — invariants hold through all transitions
// ============================================================================

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_preserves_outcome_in_canonical_range() {
    let mut s: State = kani::any();
    kani::assume(outcome_in_canonical_range(&s));
    kani::assume(comparison_bounded(&s));
    let earliest_slot: u64 = kani::any();
    let threshold_price: u64 = kani::any();
    let threshold_expo: u64 = kani::any();
    let comparison: u8 = kani::any();
    if initialize(&mut s, earliest_slot, threshold_price, threshold_expo, comparison) {
        assert!(outcome_in_canonical_range(&s),
            "outcome_in_canonical_range must hold after initialize");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_case_0_preserves_outcome_in_canonical_range() {
    let mut s: State = kani::any();
    kani::assume(outcome_in_canonical_range(&s));
    kani::assume(comparison_bounded(&s));
    let clock_slot: u64 = kani::any();
    let feed_price: u64 = kani::any();
    let feed_expo: u64 = kani::any();
    if resolve_case_0(&mut s, clock_slot, feed_price, feed_expo) {
        assert!(outcome_in_canonical_range(&s),
            "outcome_in_canonical_range must hold after resolve_case_0");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_case_1_preserves_outcome_in_canonical_range() {
    let mut s: State = kani::any();
    kani::assume(outcome_in_canonical_range(&s));
    kani::assume(comparison_bounded(&s));
    let clock_slot: u64 = kani::any();
    let feed_price: u64 = kani::any();
    let feed_expo: u64 = kani::any();
    if resolve_case_1(&mut s, clock_slot, feed_price, feed_expo) {
        assert!(outcome_in_canonical_range(&s),
            "outcome_in_canonical_range must hold after resolve_case_1");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_case_2_preserves_outcome_in_canonical_range() {
    let mut s: State = kani::any();
    kani::assume(outcome_in_canonical_range(&s));
    kani::assume(comparison_bounded(&s));
    let clock_slot: u64 = kani::any();
    let feed_price: u64 = kani::any();
    let feed_expo: u64 = kani::any();
    if resolve_case_2(&mut s, clock_slot, feed_price, feed_expo) {
        assert!(outcome_in_canonical_range(&s),
            "outcome_in_canonical_range must hold after resolve_case_2");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_case_3_preserves_outcome_in_canonical_range() {
    let mut s: State = kani::any();
    kani::assume(outcome_in_canonical_range(&s));
    kani::assume(comparison_bounded(&s));
    let clock_slot: u64 = kani::any();
    let feed_price: u64 = kani::any();
    let feed_expo: u64 = kani::any();
    if resolve_case_3(&mut s, clock_slot, feed_price, feed_expo) {
        assert!(outcome_in_canonical_range(&s),
            "outcome_in_canonical_range must hold after resolve_case_3");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_otherwise_preserves_outcome_in_canonical_range() {
    let mut s: State = kani::any();
    kani::assume(outcome_in_canonical_range(&s));
    kani::assume(comparison_bounded(&s));
    let clock_slot: u64 = kani::any();
    let feed_price: u64 = kani::any();
    let feed_expo: u64 = kani::any();
    if resolve_otherwise(&mut s, clock_slot, feed_price, feed_expo) {
        assert!(outcome_in_canonical_range(&s),
            "outcome_in_canonical_range must hold after resolve_otherwise");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_initialize_preserves_comparison_bounded() {
    let mut s: State = kani::any();
    kani::assume(outcome_in_canonical_range(&s));
    kani::assume(comparison_bounded(&s));
    let earliest_slot: u64 = kani::any();
    let threshold_price: u64 = kani::any();
    let threshold_expo: u64 = kani::any();
    let comparison: u8 = kani::any();
    if initialize(&mut s, earliest_slot, threshold_price, threshold_expo, comparison) {
        assert!(comparison_bounded(&s),
            "comparison_bounded must hold after initialize");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_case_0_preserves_comparison_bounded() {
    let mut s: State = kani::any();
    kani::assume(outcome_in_canonical_range(&s));
    kani::assume(comparison_bounded(&s));
    let clock_slot: u64 = kani::any();
    let feed_price: u64 = kani::any();
    let feed_expo: u64 = kani::any();
    if resolve_case_0(&mut s, clock_slot, feed_price, feed_expo) {
        assert!(comparison_bounded(&s),
            "comparison_bounded must hold after resolve_case_0");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_case_1_preserves_comparison_bounded() {
    let mut s: State = kani::any();
    kani::assume(outcome_in_canonical_range(&s));
    kani::assume(comparison_bounded(&s));
    let clock_slot: u64 = kani::any();
    let feed_price: u64 = kani::any();
    let feed_expo: u64 = kani::any();
    if resolve_case_1(&mut s, clock_slot, feed_price, feed_expo) {
        assert!(comparison_bounded(&s),
            "comparison_bounded must hold after resolve_case_1");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_case_2_preserves_comparison_bounded() {
    let mut s: State = kani::any();
    kani::assume(outcome_in_canonical_range(&s));
    kani::assume(comparison_bounded(&s));
    let clock_slot: u64 = kani::any();
    let feed_price: u64 = kani::any();
    let feed_expo: u64 = kani::any();
    if resolve_case_2(&mut s, clock_slot, feed_price, feed_expo) {
        assert!(comparison_bounded(&s),
            "comparison_bounded must hold after resolve_case_2");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_case_3_preserves_comparison_bounded() {
    let mut s: State = kani::any();
    kani::assume(outcome_in_canonical_range(&s));
    kani::assume(comparison_bounded(&s));
    let clock_slot: u64 = kani::any();
    let feed_price: u64 = kani::any();
    let feed_expo: u64 = kani::any();
    if resolve_case_3(&mut s, clock_slot, feed_price, feed_expo) {
        assert!(comparison_bounded(&s),
            "comparison_bounded must hold after resolve_case_3");
    }
}

#[kani::proof]
#[kani::unwind(2)]
#[kani::solver(cadical)]
fn verify_resolve_otherwise_preserves_comparison_bounded() {
    let mut s: State = kani::any();
    kani::assume(outcome_in_canonical_range(&s));
    kani::assume(comparison_bounded(&s));
    let clock_slot: u64 = kani::any();
    let feed_price: u64 = kani::any();
    let feed_expo: u64 = kani::any();
    if resolve_otherwise(&mut s, clock_slot, feed_price, feed_expo) {
        assert!(comparison_bounded(&s),
            "comparison_bounded must hold after resolve_otherwise");
    }
}

// ============================================================================
// Effect conformance — verify transition effects match spec
//
// Each proof applies a transition to symbolic state and checks that every
// field changed/unchanged matches the spec's effect: declarations.
// ============================================================================

// ============================================================================
// Cover properties — reachability via kani::cover!
// ============================================================================

#[kani::proof]
#[kani::unwind(3)]
#[kani::solver(cadical)]
fn cover_happy_path() {
    let mut s: State = kani::any();
    let earliest_slot_0: u64 = kani::any();
    let threshold_price_0: u64 = kani::any();
    let threshold_expo_0: u64 = kani::any();
    let comparison_0: u8 = kani::any();
    if initialize(&mut s, earliest_slot_0, threshold_price_0, threshold_expo_0, comparison_0) {
        kani::cover!(resolve_otherwise(&mut s, kani::any(), kani::any(), kani::any()), "happy_path trace is reachable");
    }
}

// ---- GENERATED BY QEDGEN — DO NOT EDIT BELOW THIS LINE ----
