// ---- GENERATED BY QEDGEN ----
//
// Proptest harnesses — property-based testing for the spec's state machine.
// Tier 1 of the verification waterfall: finds counterexamples in milliseconds.
//
//   Proptest: random testing, fast counterexamples (~100ms)
//   Kani:     bounded model checking, exhaustive within bounds (~5-30s)
//   Lean:     mathematical proof, universal guarantees (minutes-hours)
//
// To run:  cargo test --test proptest
// Deep:    PROPTEST_CASES=10000 cargo test --test proptest
// ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----

use proptest::prelude::*;

const COMPARISON_GTE: u8 = 0;
const COMPARISON_LT: u8 = 1;

#[derive(Debug, Clone, Copy)]
struct State {
    initialized: u8,
    earliest_slot: u64,
    threshold_price: u64,
    threshold_expo: u64,
    comparison: u8,
    last_returned: u8,
}

prop_compose! {
    fn arb_State()(initialized in 0u8..=255u8, earliest_slot in 0u64..=u64::MAX, threshold_price in 0u64..=u64::MAX, threshold_expo in 0u64..=u64::MAX, comparison in 0u8..=255u8, last_returned in 0u8..=255u8) -> State {
        State {
            initialized,
            earliest_slot,
            threshold_price,
            threshold_expo,
            comparison,
            last_returned,
        }
    }
}

#[derive(Debug, Clone, Copy)]
struct State {
}

/// Proptest strategy for generating arbitrary State values.
fn arb_state() -> impl Strategy<Value = State> {
    (
,
    ).prop_map(|()| State {
    })
}

/// Boundary-biased strategy for guard rejection tests.
fn arb_boundary_state() -> impl Strategy<Value = State> {
    (
,
    ).prop_map(|()| State {
    })
}

/// outcome_in_canonical_range: s.last_returned ≤ 3
fn outcome_in_canonical_range(s: &State) -> bool {
    s.last_returned <= 3
}

/// comparison_bounded: s.initialized = 0 ∨ (s.comparison = 0 ∨ s.comparison = 1)
fn comparison_bounded(s: &State) -> bool {
    (s.initialized == 0) || (((s.comparison == 0) || (s.comparison == 1)))
}

fn initialize(s: &mut State, earliest_slot: u64, threshold_price: u64, threshold_expo: u64, comparison: u8) -> bool {
    if !(s.initialized == 0 && comparison <= 1) {
        return false;
    }
    s.initialized = 1;
    s.earliest_slot = earliest_slot;
    s.threshold_price = threshold_price;
    s.threshold_expo = threshold_expo;
    s.comparison = comparison;
    true
}

fn resolve_case_0(s: &mut State, clock_slot: u64, feed_price: u64, feed_expo: u64) -> bool {
    if !(clock_slot < s.earliest_slot) {
        return false;
    }
    s.last_returned = 0;
    true
}

fn resolve_case_1(s: &mut State, clock_slot: u64, feed_price: u64, feed_expo: u64) -> bool {
    if !(!(clock_slot < s.earliest_slot) && feed_expo != s.threshold_expo) {
        return false;
    }
    s.last_returned = 3;
    true
}

fn resolve_case_2(s: &mut State, clock_slot: u64, feed_price: u64, feed_expo: u64) -> bool {
    if !(!(clock_slot < s.earliest_slot) && !(feed_expo != s.threshold_expo) && (s.comparison == 0) && (feed_price >= s.threshold_price)) {
        return false;
    }
    s.last_returned = 1;
    true
}

fn resolve_case_3(s: &mut State, clock_slot: u64, feed_price: u64, feed_expo: u64) -> bool {
    if !(!(clock_slot < s.earliest_slot) && !(feed_expo != s.threshold_expo) && !((s.comparison == 0) && (feed_price >= s.threshold_price)) && (s.comparison == 1) && (feed_price < s.threshold_price)) {
        return false;
    }
    s.last_returned = 1;
    true
}

fn resolve_otherwise(s: &mut State, clock_slot: u64, feed_price: u64, feed_expo: u64) -> bool {
    if !(!(clock_slot < s.earliest_slot) && !(feed_expo != s.threshold_expo) && !((s.comparison == 0) && (feed_price >= s.threshold_price)) && !((s.comparison == 1) && (feed_price < s.threshold_price))) {
        return false;
    }
    s.last_returned = 2;
    true
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn initialize_preserves_outcome_in_canonical_range(s in arb_state(), earliest_slot in 0u64..=u64::MAX, threshold_price in 0u64..=u64::MAX, threshold_expo in 0u64..=u64::MAX, comparison in 0u8..=u8::MAX) {
        let mut s = s;
        prop_assume!(outcome_in_canonical_range(&s));
        prop_assume!(comparison_bounded(&s));
        if initialize(&mut s, earliest_slot, threshold_price, threshold_expo, comparison) {
            prop_assert!(outcome_in_canonical_range(&s),
                "outcome_in_canonical_range must hold after initialize");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_case_0_preserves_outcome_in_canonical_range(s in arb_state(), clock_slot in 0u64..=u64::MAX, feed_price in 0u64..=u64::MAX, feed_expo in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(outcome_in_canonical_range(&s));
        prop_assume!(comparison_bounded(&s));
        if resolve_case_0(&mut s, clock_slot, feed_price, feed_expo) {
            prop_assert!(outcome_in_canonical_range(&s),
                "outcome_in_canonical_range must hold after resolve_case_0");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_case_1_preserves_outcome_in_canonical_range(s in arb_state(), clock_slot in 0u64..=u64::MAX, feed_price in 0u64..=u64::MAX, feed_expo in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(outcome_in_canonical_range(&s));
        prop_assume!(comparison_bounded(&s));
        if resolve_case_1(&mut s, clock_slot, feed_price, feed_expo) {
            prop_assert!(outcome_in_canonical_range(&s),
                "outcome_in_canonical_range must hold after resolve_case_1");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_case_2_preserves_outcome_in_canonical_range(s in arb_state(), clock_slot in 0u64..=u64::MAX, feed_price in 0u64..=u64::MAX, feed_expo in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(outcome_in_canonical_range(&s));
        prop_assume!(comparison_bounded(&s));
        if resolve_case_2(&mut s, clock_slot, feed_price, feed_expo) {
            prop_assert!(outcome_in_canonical_range(&s),
                "outcome_in_canonical_range must hold after resolve_case_2");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_case_3_preserves_outcome_in_canonical_range(s in arb_state(), clock_slot in 0u64..=u64::MAX, feed_price in 0u64..=u64::MAX, feed_expo in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(outcome_in_canonical_range(&s));
        prop_assume!(comparison_bounded(&s));
        if resolve_case_3(&mut s, clock_slot, feed_price, feed_expo) {
            prop_assert!(outcome_in_canonical_range(&s),
                "outcome_in_canonical_range must hold after resolve_case_3");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_otherwise_preserves_outcome_in_canonical_range(s in arb_state(), clock_slot in 0u64..=u64::MAX, feed_price in 0u64..=u64::MAX, feed_expo in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(outcome_in_canonical_range(&s));
        prop_assume!(comparison_bounded(&s));
        if resolve_otherwise(&mut s, clock_slot, feed_price, feed_expo) {
            prop_assert!(outcome_in_canonical_range(&s),
                "outcome_in_canonical_range must hold after resolve_otherwise");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn initialize_preserves_comparison_bounded(s in arb_state(), earliest_slot in 0u64..=u64::MAX, threshold_price in 0u64..=u64::MAX, threshold_expo in 0u64..=u64::MAX, comparison in 0u8..=u8::MAX) {
        let mut s = s;
        prop_assume!(outcome_in_canonical_range(&s));
        prop_assume!(comparison_bounded(&s));
        if initialize(&mut s, earliest_slot, threshold_price, threshold_expo, comparison) {
            prop_assert!(comparison_bounded(&s),
                "comparison_bounded must hold after initialize");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_case_0_preserves_comparison_bounded(s in arb_state(), clock_slot in 0u64..=u64::MAX, feed_price in 0u64..=u64::MAX, feed_expo in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(outcome_in_canonical_range(&s));
        prop_assume!(comparison_bounded(&s));
        if resolve_case_0(&mut s, clock_slot, feed_price, feed_expo) {
            prop_assert!(comparison_bounded(&s),
                "comparison_bounded must hold after resolve_case_0");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_case_1_preserves_comparison_bounded(s in arb_state(), clock_slot in 0u64..=u64::MAX, feed_price in 0u64..=u64::MAX, feed_expo in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(outcome_in_canonical_range(&s));
        prop_assume!(comparison_bounded(&s));
        if resolve_case_1(&mut s, clock_slot, feed_price, feed_expo) {
            prop_assert!(comparison_bounded(&s),
                "comparison_bounded must hold after resolve_case_1");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_case_2_preserves_comparison_bounded(s in arb_state(), clock_slot in 0u64..=u64::MAX, feed_price in 0u64..=u64::MAX, feed_expo in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(outcome_in_canonical_range(&s));
        prop_assume!(comparison_bounded(&s));
        if resolve_case_2(&mut s, clock_slot, feed_price, feed_expo) {
            prop_assert!(comparison_bounded(&s),
                "comparison_bounded must hold after resolve_case_2");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_case_3_preserves_comparison_bounded(s in arb_state(), clock_slot in 0u64..=u64::MAX, feed_price in 0u64..=u64::MAX, feed_expo in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(outcome_in_canonical_range(&s));
        prop_assume!(comparison_bounded(&s));
        if resolve_case_3(&mut s, clock_slot, feed_price, feed_expo) {
            prop_assert!(comparison_bounded(&s),
                "comparison_bounded must hold after resolve_case_3");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_otherwise_preserves_comparison_bounded(s in arb_state(), clock_slot in 0u64..=u64::MAX, feed_price in 0u64..=u64::MAX, feed_expo in 0u64..=u64::MAX) {
        let mut s = s;
        prop_assume!(outcome_in_canonical_range(&s));
        prop_assume!(comparison_bounded(&s));
        if resolve_otherwise(&mut s, clock_slot, feed_price, feed_expo) {
            prop_assert!(comparison_bounded(&s),
                "comparison_bounded must hold after resolve_otherwise");
        }
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn initialize_rejects_invalid(s in arb_boundary_state(), earliest_slot in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], threshold_price in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], threshold_expo in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], comparison in prop_oneof![0u8..=3u8, 252u8..=255u8]) {
        let mut s = s;
        prop_assume!(!(s.initialized == 0 && comparison <= 1));
        prop_assert!(!initialize(&mut s, earliest_slot, threshold_price, threshold_expo, comparison),
            "initialize must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_case_0_rejects_invalid(s in arb_boundary_state(), clock_slot in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], feed_price in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], feed_expo in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX]) {
        let mut s = s;
        prop_assume!(!(clock_slot < s.earliest_slot));
        prop_assert!(!resolve_case_0(&mut s, clock_slot, feed_price, feed_expo),
            "resolve_case_0 must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_case_1_rejects_invalid(s in arb_boundary_state(), clock_slot in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], feed_price in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], feed_expo in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX]) {
        let mut s = s;
        prop_assume!(!(!(clock_slot < s.earliest_slot) && feed_expo != s.threshold_expo));
        prop_assert!(!resolve_case_1(&mut s, clock_slot, feed_price, feed_expo),
            "resolve_case_1 must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_case_2_rejects_invalid(s in arb_boundary_state(), clock_slot in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], feed_price in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], feed_expo in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX]) {
        let mut s = s;
        prop_assume!(!(!(clock_slot < s.earliest_slot) && !(feed_expo != s.threshold_expo) && (s.comparison == 0) && (feed_price >= s.threshold_price)));
        prop_assert!(!resolve_case_2(&mut s, clock_slot, feed_price, feed_expo),
            "resolve_case_2 must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_case_3_rejects_invalid(s in arb_boundary_state(), clock_slot in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], feed_price in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], feed_expo in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX]) {
        let mut s = s;
        prop_assume!(!(!(clock_slot < s.earliest_slot) && !(feed_expo != s.threshold_expo) && !((s.comparison == 0) && (feed_price >= s.threshold_price)) && (s.comparison == 1) && (feed_price < s.threshold_price)));
        prop_assert!(!resolve_case_3(&mut s, clock_slot, feed_price, feed_expo),
            "resolve_case_3 must reject when guard is violated");
    }
}

proptest! {
    #![proptest_config(ProptestConfig { max_global_rejects: 65536, ..ProptestConfig::with_cases(256) })]
    #[test]
    fn resolve_otherwise_rejects_invalid(s in arb_boundary_state(), clock_slot in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], feed_price in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX], feed_expo in prop_oneof![0u64..=3u64, (u64::MAX - 3)..=u64::MAX]) {
        let mut s = s;
        prop_assume!(!(!(clock_slot < s.earliest_slot) && !(feed_expo != s.threshold_expo) && !((s.comparison == 0) && (feed_price >= s.threshold_price)) && !((s.comparison == 1) && (feed_price < s.threshold_price))));
        prop_assert!(!resolve_otherwise(&mut s, clock_slot, feed_price, feed_expo),
            "resolve_otherwise must reject when guard is violated");
    }
}

#[derive(Debug, Clone)]
enum Op {
    Initialize(u64, u64, u64, u8),
    ResolveCase0(u64, u64, u64),
    ResolveCase1(u64, u64, u64),
    ResolveCase2(u64, u64, u64),
    ResolveCase3(u64, u64, u64),
    ResolveOtherwise(u64, u64, u64),
}

fn arb_op() -> impl Strategy<Value = Op> {
    prop_oneof![
        (0u64..=u64::MAX, 0u64..=u64::MAX, 0u64..=u64::MAX, 0u8..=u8::MAX).prop_map(|(earliest_slot, threshold_price, threshold_expo, comparison)| Op::Initialize(earliest_slot, threshold_price, threshold_expo, comparison)),
        (0u64..=u64::MAX, 0u64..=u64::MAX, 0u64..=u64::MAX).prop_map(|(clock_slot, feed_price, feed_expo)| Op::ResolveCase0(clock_slot, feed_price, feed_expo)),
        (0u64..=u64::MAX, 0u64..=u64::MAX, 0u64..=u64::MAX).prop_map(|(clock_slot, feed_price, feed_expo)| Op::ResolveCase1(clock_slot, feed_price, feed_expo)),
        (0u64..=u64::MAX, 0u64..=u64::MAX, 0u64..=u64::MAX).prop_map(|(clock_slot, feed_price, feed_expo)| Op::ResolveCase2(clock_slot, feed_price, feed_expo)),
        (0u64..=u64::MAX, 0u64..=u64::MAX, 0u64..=u64::MAX).prop_map(|(clock_slot, feed_price, feed_expo)| Op::ResolveCase3(clock_slot, feed_price, feed_expo)),
        (0u64..=u64::MAX, 0u64..=u64::MAX, 0u64..=u64::MAX).prop_map(|(clock_slot, feed_price, feed_expo)| Op::ResolveOtherwise(clock_slot, feed_price, feed_expo)),
    ]
}

fn apply_op(s: &mut State, op: &Op) -> bool {
    match op {
        Op::Initialize(earliest_slot, threshold_price, threshold_expo, comparison) => initialize(s, *earliest_slot, *threshold_price, *threshold_expo, *comparison),
        Op::ResolveCase0(clock_slot, feed_price, feed_expo) => resolve_case_0(s, *clock_slot, *feed_price, *feed_expo),
        Op::ResolveCase1(clock_slot, feed_price, feed_expo) => resolve_case_1(s, *clock_slot, *feed_price, *feed_expo),
        Op::ResolveCase2(clock_slot, feed_price, feed_expo) => resolve_case_2(s, *clock_slot, *feed_price, *feed_expo),
        Op::ResolveCase3(clock_slot, feed_price, feed_expo) => resolve_case_3(s, *clock_slot, *feed_price, *feed_expo),
        Op::ResolveOtherwise(clock_slot, feed_price, feed_expo) => resolve_otherwise(s, *clock_slot, *feed_price, *feed_expo),
    }
}

fn assert_all_properties(s: &State, context: &str) {
    assert!(outcome_in_canonical_range(s), "{} violated: outcome_in_canonical_range", context);
    assert!(comparison_bounded(s), "{} violated: comparison_bounded", context);
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(256))]
    #[test]
    fn state_machine_sequence(ops in proptest::collection::vec(arb_op(), 1..20)) {
        let mut s = State {
        };
        for (i, op) in ops.iter().enumerate() {
            if apply_op(&mut s, op) {
                // Check all properties after each successful transition
                prop_assert!(outcome_in_canonical_range(&s),
                    "outcome_in_canonical_range violated after op {:?} (step {})", op, i);
                prop_assert!(comparison_bounded(&s),
                    "comparison_bounded violated after op {:?} (step {})", op, i);
            }
        }
    }
}
